import { notFound } from "next/navigation";
import { prisma } from "@/lib/db/prisma";
import { requireUser } from "@/lib/auth/session";
import { PageHeader, PageShell } from "@/components/shell/PageHeader";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { Avatar } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Sparkline } from "@/components/ui/sparkline";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { formatDate } from "@/lib/utils/format";

interface PageProps {
  params: { id: string };
}

export default async function PatientChartPage({ params }: PageProps) {
  const user = await requireUser();

  const patient = await prisma.patient.findFirst({
    where: {
      id: params.id,
      organizationId: user.organizationId!,
      deletedAt: null,
    },
    include: {
      chartSummary: true,
      outcomeLogs: { orderBy: { loggedAt: "asc" }, take: 60 },
      encounters: {
        orderBy: { scheduledFor: "desc" },
        include: { notes: true },
      },
      documents: {
        where: { deletedAt: null },
        orderBy: { createdAt: "desc" },
        take: 10,
      },
      assessmentResponses: {
        include: { assessment: true },
        orderBy: { submittedAt: "desc" },
        take: 5,
      },
    },
  });

  if (!patient) notFound();

  const pain = patient.outcomeLogs.filter((l) => l.metric === "pain").map((l) => l.value);
  const sleep = patient.outcomeLogs.filter((l) => l.metric === "sleep").map((l) => l.value);

  return (
    <PageShell maxWidth="max-w-[1280px]">
      <PageHeader
        eyebrow="Patient chart"
        title={`${patient.firstName} ${patient.lastName}`}
        description={patient.presentingConcerns ?? undefined}
        actions={
          <>
            <Button variant="secondary">Message</Button>
            <Button>Start visit</Button>
          </>
        }
      />

      {/* Chart header strip */}
      <Card className="mb-6">
        <CardContent className="pt-6">
          <div className="flex flex-wrap items-center gap-6">
            <Avatar firstName={patient.firstName} lastName={patient.lastName} size="lg" />
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2 flex-wrap">
                <p className="text-sm font-medium text-text">
                  {patient.firstName} {patient.lastName}
                </p>
                <Badge tone="neutral">{patient.status}</Badge>
                {patient.chartSummary && (
                  <Badge tone="accent">
                    Chart {patient.chartSummary.completenessScore}% ready
                  </Badge>
                )}
                {patient.qualificationStatus !== "unknown" && (
                  <Badge tone="info">{patient.qualificationStatus}</Badge>
                )}
              </div>
              <p className="text-xs text-text-subtle mt-1">
                DOB {formatDate(patient.dateOfBirth)} · {patient.email ?? "—"}
              </p>
            </div>
          </div>
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Main column */}
        <div className="lg:col-span-2 space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Chart summary</CardTitle>
              <CardDescription>
                Generated by the intake agent. Refreshed on every intake update.
              </CardDescription>
            </CardHeader>
            <CardContent>
              {patient.chartSummary ? (
                <div className="prose-clinical whitespace-pre-wrap">
                  {patient.chartSummary.summaryMd}
                </div>
              ) : (
                <p className="text-sm text-text-muted">
                  No chart summary yet. It will be generated as intake is completed.
                </p>
              )}
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Outcome trends</CardTitle>
              <CardDescription>Recent symptom and sleep data.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-2 gap-6">
                <div>
                  <p className="text-xs text-text-subtle mb-2">Pain (0-10)</p>
                  <Sparkline data={pain.length > 1 ? pain : [0, 0]} width={280} height={60} />
                </div>
                <div>
                  <p className="text-xs text-text-subtle mb-2">Sleep (0-10)</p>
                  <Sparkline data={sleep.length > 1 ? sleep : [0, 0]} width={280} height={60} />
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Timeline</CardTitle>
              <CardDescription>Encounters, notes, and uploads.</CardDescription>
            </CardHeader>
            <CardContent>
              <ul className="space-y-4">
                {patient.encounters.map((e) => (
                  <li key={e.id} className="flex gap-4">
                    <div className="w-24 shrink-0 text-xs text-text-subtle tabular-nums pt-0.5">
                      {formatDate(e.scheduledFor ?? e.createdAt)}
                    </div>
                    <div className="flex-1 min-w-0 pb-4 border-l border-border pl-4 relative">
                      <div className="absolute -left-1.5 top-1 h-2.5 w-2.5 rounded-full bg-accent" />
                      <p className="text-sm font-medium text-text">
                        {e.modality} visit · {e.status}
                      </p>
                      {e.reason && (
                        <p className="text-xs text-text-muted mt-0.5">{e.reason}</p>
                      )}
                      {e.notes[0] && (
                        <Badge tone="neutral" className="mt-2">
                          Note: {e.notes[0].status}
                        </Badge>
                      )}
                    </div>
                  </li>
                ))}
                {patient.encounters.length === 0 && (
                  <li className="text-sm text-text-muted">No visits on record yet.</li>
                )}
              </ul>
            </CardContent>
          </Card>
        </div>

        {/* Side column */}
        <div className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Documents</CardTitle>
            </CardHeader>
            <CardContent>
              {patient.documents.length === 0 ? (
                <p className="text-sm text-text-muted">No documents uploaded.</p>
              ) : (
                <ul className="space-y-2">
                  {patient.documents.map((d) => (
                    <li key={d.id} className="text-sm text-text truncate">
                      <span className="text-text-subtle tabular-nums mr-2">
                        {formatDate(d.createdAt)}
                      </span>
                      {d.originalName}
                    </li>
                  ))}
                </ul>
              )}
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Assessments</CardTitle>
            </CardHeader>
            <CardContent>
              {patient.assessmentResponses.length === 0 ? (
                <p className="text-sm text-text-muted">No responses yet.</p>
              ) : (
                <ul className="space-y-2">
                  {patient.assessmentResponses.map((r) => (
                    <li key={r.id} className="flex items-center justify-between text-sm">
                      <span className="text-text">{r.assessment.title}</span>
                      <span className="text-text-muted tabular-nums">
                        {r.score?.toFixed(0) ?? "—"}
                      </span>
                    </li>
                  ))}
                </ul>
              )}
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Research</CardTitle>
              <CardDescription>Contextual evidence for this patient.</CardDescription>
            </CardHeader>
            <CardContent>
              <Button size="sm" variant="secondary" className="w-full">
                Open research panel
              </Button>
            </CardContent>
          </Card>
        </div>
      </div>
    </PageShell>
  );
}
