import { prisma } from "@/lib/db/prisma";
import { PageHeader, PageShell } from "@/components/shell/PageHeader";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { EmptyState } from "@/components/ui/empty-state";
import { LeafSprig } from "@/components/ui/ornament";
import { ResearchSearchForm } from "./research-form";
import { formatRelative } from "@/lib/utils/format";

export const metadata = { title: "Research" };

export default async function ResearchConsolePage({
  searchParams,
}: {
  searchParams: { q?: string; id?: string };
}) {
  const recent = await prisma.researchQuery.findMany({
    orderBy: { createdAt: "desc" },
    take: 8,
    include: { results: { orderBy: { rank: "asc" } } },
  });

  const selected = searchParams.id
    ? recent.find((r) => r.id === searchParams.id) ?? null
    : recent[0] ?? null;

  return (
    <PageShell maxWidth="max-w-[1320px]">
      <PageHeader
        eyebrow="Research"
        title="Evidence at the point of care"
        description="Search the corpus. Summaries are generated by the Research Agent and traceable to source."
      />

      {/* Combo Wheel link card */}
      <Card tone="ambient" className="mb-6">
        <CardContent className="py-5 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <LeafSprig size={20} className="text-accent" />
            <div>
              <p className="text-sm font-medium text-text">Cannabis Combo Wheel</p>
              <p className="text-xs text-text-muted mt-0.5">Interactive tool: combine cannabinoids + terpenes to see therapeutic profiles</p>
            </div>
          </div>
          <a href="/clinic/research/combo-wheel" className="inline-flex items-center gap-2 px-4 py-2 rounded-md text-sm font-medium bg-accent text-accent-ink hover:bg-accent/90 transition-colors">
            Open wheel &rarr;
          </a>
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-6">
          {/* Search card */}
          <Card tone="raised">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <LeafSprig size={16} className="text-accent/80" />
                Search the evidence
              </CardTitle>
              <CardDescription>
                Try: &quot;neuropathic pain&quot;, &quot;sleep insomnia&quot;, &quot;anxiety cbd&quot;, &quot;nausea oncology&quot;.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <ResearchSearchForm />
            </CardContent>
          </Card>

          {/* Results */}
          {selected ? (
            <Card tone="raised">
              <CardHeader>
                <div className="flex items-center justify-between gap-4">
                  <div>
                    <CardTitle className="font-display text-xl">&quot;{selected.queryText}&quot;</CardTitle>
                    <CardDescription>
                      {selected.results.length} result{selected.results.length === 1 ? "" : "s"} found
                    </CardDescription>
                  </div>
                  <Badge tone="accent">
                    {selected.results.length > 0 ? "Evidence found" : "No matches"}
                  </Badge>
                </div>
              </CardHeader>
              <CardContent>
                {selected.results.length === 0 ? (
                  <div className="py-4">
                    <p className="text-sm text-text-muted">
                      No matches in the indexed corpus for this query. Try broadening the terms.
                    </p>
                  </div>
                ) : (
                  <ul className="divide-y divide-border/60 -mx-6">
                    {selected.results.map((r, idx) => (
                      <li key={r.id} className="px-6 py-5 hover:bg-surface-muted/30 transition-colors">
                        <div className="flex items-start gap-4">
                          <span className="font-display text-2xl text-border-strong/70 select-none tabular-nums leading-none mt-0.5 w-6 text-center">
                            {idx + 1}
                          </span>
                          <div className="flex-1 min-w-0">
                            {r.url ? (
                              <a
                                href={r.url}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="font-display text-base text-accent leading-snug hover:underline"
                              >
                                {r.title} ↗
                              </a>
                            ) : (
                              <p className="font-display text-base text-text leading-snug">
                                {r.title}
                              </p>
                            )}
                            <p className="text-xs text-text-subtle mt-1.5 font-mono">
                              {r.citation}
                              {r.pmid && (
                                <a
                                  href={`https://pubmed.ncbi.nlm.nih.gov/${r.pmid}/`}
                                  target="_blank"
                                  rel="noopener noreferrer"
                                  className="ml-2 text-accent hover:underline"
                                >
                                  PMID: {r.pmid}
                                </a>
                              )}
                            </p>
                            <p className="text-sm text-text-muted mt-3 leading-relaxed">
                              {r.summary}
                            </p>
                          </div>
                        </div>
                      </li>
                    ))}
                  </ul>
                )}
              </CardContent>
            </Card>
          ) : (
            <EmptyState
              title="Run your first search"
              description="Type a symptom, condition, or treatment keyword to query the evidence corpus."
            />
          )}
        </div>

        {/* Sidebar */}
        <div className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Recent queries</CardTitle>
              <CardDescription>{recent.length} saved searches.</CardDescription>
            </CardHeader>
            <CardContent>
              {recent.length === 0 ? (
                <p className="text-sm text-text-muted">No searches yet.</p>
              ) : (
                <ul className="space-y-3 -mx-2">
                  {recent.map((q) => {
                    const isSelected = selected?.id === q.id;
                    return (
                      <li key={q.id}>
                        <a
                          href={`?id=${q.id}`}
                          className={`
                            block px-3 py-2.5 rounded-lg transition-colors
                            ${
                              isSelected
                                ? "bg-accent-soft border border-accent/20"
                                : "hover:bg-surface-muted"
                            }
                          `}
                        >
                          <p className={`text-sm font-medium ${isSelected ? "text-accent" : "text-text"}`}>
                            {q.queryText}
                          </p>
                          <div className="flex items-center gap-2 mt-1">
                            <Badge tone={q.results.length > 0 ? "accent" : "neutral"}>
                              {q.results.length} hit{q.results.length === 1 ? "" : "s"}
                            </Badge>
                            <span className="text-[10px] text-text-subtle">
                              {formatRelative(q.createdAt)}
                            </span>
                          </div>
                        </a>
                      </li>
                    );
                  })}
                </ul>
              )}
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>About the corpus</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-text-muted leading-relaxed">
                Results are drawn from a curated index of peer-reviewed cannabis
                studies, augmented by the live PubMed E-utilities API. The
                Research Synthesizer Agent matches keywords, ranks relevance,
                and generates a summary with traceable citations.
              </p>
              <p className="text-xs text-text-subtle mt-3">
                Every cited article links out to PubMed in a new tab, so the
                full abstract is one click from the chart.
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </PageShell>
  );
}
