/**
 * EMR-110 — AI Patient Education Sheets
 *
 * Generates personalized, third-grade-reading-level handouts that the
 * patient gets after a visit. Each sheet is built from:
 *
 *   • the diagnosis (ICD-10) — provides the structural template,
 *   • the dispensary product or medication — fills in dose, timing,
 *     side-effect copy,
 *   • the patient's age band — picks pictograms, vocabulary level, and
 *     guardian-facing addenda where appropriate,
 *   • the patient's preferred language — EN / ES (more added per
 *     population needs).
 *
 * The model client is *optional*. When it's available the sheet uses an
 * LLM to produce a warm, fairytale-style summary. When it isn't (CI,
 * cost guardrails) it falls back to a deterministic template. The shape
 * of the result is identical either way so callers don't branch.
 *
 * Each sheet is auditable: the inputs, model used (if any), and the
 * generated text are persisted to the patient record so a clinician can
 * later see exactly what the patient took home.
 *
 * Dr. Patel directive: every sheet ends with the patient outcome-tracking
 * checklist (emoji-first sentiment + 1-10 scale) so research data continues
 * to flow from the at-home setting.
 */

import type { ModelClient } from "@/lib/orchestration/types";
import type { AgeBand } from "@/lib/utils/patient-age";

// ---------------------------------------------------------------------------
// Inputs / outputs
// ---------------------------------------------------------------------------

export interface PatientContextForEducation {
  firstName: string;
  preferredLanguage?: "en" | "es";
  ageBand: AgeBand;
  age: number | null;
  /** True when the patient is a minor — adds a guardian note. */
  hasGuardian?: boolean;
  guardianName?: string | null;
  /** Important things to call out (allergies, advanced directives, etc.). */
  flags?: string[];
}

export interface EducationSheetTopic {
  /** ICD-10 the sheet is built around. */
  icd10: string;
  diagnosisLabel: string;
  /** Friendly, plain-language title. */
  title: string;
  /** Optional medication / cannabis product the sheet is about. */
  product?: {
    name: string;
    formulation?: string;
    cannabinoids?: string[];
    dose?: string;
    schedule?: string;
  };
  /** Visit-specific context the clinician wants the patient to remember. */
  visitNotes?: string;
}

export interface EducationSheetSection {
  id: string;
  emoji: string;
  heading: string;
  body: string;
  /** Bulleted action items the patient should take this week. */
  actions?: string[];
}

export interface EducationSheet {
  id: string;
  generatedAt: string;
  language: "en" | "es";
  topic: EducationSheetTopic;
  sections: EducationSheetSection[];
  /** Patient outcome-tracking checklist — emoji + 1-10 prompts. */
  outcomeChecklist: OutcomePrompt[];
  /** Stub references the clinician can verify (Cochrane / NIH). */
  references: string[];
  /** Whether the body was generated by a model or template. */
  source: "llm" | "template";
  modelLabel?: string;
}

export interface OutcomePrompt {
  id: string;
  /** "How was your sleep?" / "Pain level today?" etc. */
  question: string;
  /** Three faces the patient taps. */
  faces: ["😞", "😐", "😀"];
  /** 1-10 scale anchors. */
  scale: { min: string; max: string };
}

// ---------------------------------------------------------------------------
// Topic library — small starter; the real library lives in
// `lib/domain/cannabis-education.ts`.
// ---------------------------------------------------------------------------

const SECTION_BLUEPRINT_BY_ICD: Record<
  string,
  { sectionId: string; emoji: string; heading: string }[]
> = {
  // chronic pain
  "G89.29": [
    { sectionId: "what", emoji: "💡", heading: "What's going on" },
    { sectionId: "why_cannabis", emoji: "🌿", heading: "Why cannabis can help" },
    { sectionId: "how_to_use", emoji: "📅", heading: "How to use your medicine" },
    { sectionId: "watch_for", emoji: "👀", heading: "Watch for these" },
    { sectionId: "lifestyle", emoji: "🚶", heading: "Movement + sleep tips" },
  ],
  // generalized anxiety
  "F41.1": [
    { sectionId: "what", emoji: "💡", heading: "What's going on" },
    { sectionId: "why_cannabis", emoji: "🌿", heading: "How cannabis fits in" },
    { sectionId: "how_to_use", emoji: "📅", heading: "How to use your medicine" },
    { sectionId: "watch_for", emoji: "👀", heading: "Watch for these" },
    { sectionId: "calm_tools", emoji: "🌬️", heading: "Calming tools to try" },
  ],
  // insomnia
  "G47.00": [
    { sectionId: "what", emoji: "💡", heading: "About sleep" },
    { sectionId: "why_cannabis", emoji: "🌙", heading: "What cannabis does at night" },
    { sectionId: "how_to_use", emoji: "🛏️", heading: "Your bedtime routine" },
    { sectionId: "watch_for", emoji: "👀", heading: "Watch for these" },
    { sectionId: "lifestyle", emoji: "☀️", heading: "Helpful daytime habits" },
  ],
  // PTSD
  "F43.10": [
    { sectionId: "what", emoji: "💡", heading: "What's going on" },
    { sectionId: "why_cannabis", emoji: "🌿", heading: "How cannabis can help" },
    { sectionId: "grounding", emoji: "🌳", heading: "Grounding tools" },
    { sectionId: "how_to_use", emoji: "📅", heading: "Your medicine plan" },
    { sectionId: "watch_for", emoji: "👀", heading: "Watch for these" },
  ],
};

const DEFAULT_BLUEPRINT = [
  { sectionId: "what", emoji: "💡", heading: "What's going on" },
  { sectionId: "plan", emoji: "📅", heading: "Your plan" },
  { sectionId: "watch_for", emoji: "👀", heading: "Watch for these" },
  { sectionId: "questions", emoji: "🙋", heading: "Bring these up next time" },
];

// ---------------------------------------------------------------------------
// Outcome checklists — keyed by primary symptom inferred from ICD-10.
// ---------------------------------------------------------------------------

const OUTCOME_PROMPT_LIBRARY: Record<string, OutcomePrompt> = {
  pain: {
    id: "pain",
    question: "How is your pain today?",
    faces: ["😞", "😐", "😀"],
    scale: { min: "10 = worst pain ever", max: "1 = no pain" },
  },
  sleep: {
    id: "sleep",
    question: "How did you sleep last night?",
    faces: ["😞", "😐", "😀"],
    scale: { min: "1 = barely slept", max: "10 = slept great" },
  },
  anxiety: {
    id: "anxiety",
    question: "How is your anxiety today?",
    faces: ["😞", "😐", "😀"],
    scale: { min: "10 = worst anxiety ever", max: "1 = totally calm" },
  },
  mood: {
    id: "mood",
    question: "How is your mood?",
    faces: ["😞", "😐", "😀"],
    scale: { min: "1 = very low", max: "10 = very good" },
  },
  side_effects: {
    id: "side_effects",
    question: "Any side effects since last check-in?",
    faces: ["😞", "😐", "😀"],
    scale: { min: "10 = strong side effects", max: "1 = no side effects" },
  },
};

function outcomeChecklistForIcd(icd: string): OutcomePrompt[] {
  const code = icd.toUpperCase();
  if (code.startsWith("G89") || code.startsWith("M54") || code === "M79.7" || code.startsWith("G43")) {
    return [OUTCOME_PROMPT_LIBRARY.pain, OUTCOME_PROMPT_LIBRARY.side_effects];
  }
  if (code.startsWith("G47")) {
    return [OUTCOME_PROMPT_LIBRARY.sleep, OUTCOME_PROMPT_LIBRARY.side_effects];
  }
  if (
    code.startsWith("F41") ||
    code.startsWith("F40") ||
    code.startsWith("F43")
  ) {
    return [
      OUTCOME_PROMPT_LIBRARY.anxiety,
      OUTCOME_PROMPT_LIBRARY.mood,
      OUTCOME_PROMPT_LIBRARY.sleep,
      OUTCOME_PROMPT_LIBRARY.side_effects,
    ];
  }
  if (code.startsWith("F32") || code.startsWith("F33")) {
    return [
      OUTCOME_PROMPT_LIBRARY.mood,
      OUTCOME_PROMPT_LIBRARY.sleep,
      OUTCOME_PROMPT_LIBRARY.side_effects,
    ];
  }
  return [OUTCOME_PROMPT_LIBRARY.mood, OUTCOME_PROMPT_LIBRARY.side_effects];
}

// ---------------------------------------------------------------------------
// Template-mode body
// ---------------------------------------------------------------------------

function templateBody(
  sectionId: string,
  topic: EducationSheetTopic,
  patient: PatientContextForEducation,
): { body: string; actions?: string[] } {
  const product = topic.product?.name ?? "your medicine";
  const dose = topic.product?.dose ?? "the dose your doctor prescribed";
  const schedule = topic.product?.schedule ?? "the times your doctor wrote down";
  const name = patient.firstName;

  switch (sectionId) {
    case "what":
      return {
        body:
          `Hey ${name} — your visit today was about ${topic.diagnosisLabel.toLowerCase()}. ` +
          `That just means ${plainLanguageForDiagnosis(topic.icd10)}.`,
      };
    case "why_cannabis":
      return {
        body:
          `Cannabis works through your body's own endocannabinoid system. For ${topic.diagnosisLabel.toLowerCase()}, ` +
          `the goal is to take the edge off without making you feel out of it. We picked ${product} because it fits that goal.`,
      };
    case "how_to_use":
      return {
        body:
          `Take ${dose}, ${schedule}. ` +
          `Start at the lower end if you've never tried it before — small wins build trust with this medicine.`,
        actions: [
          `Take your first dose at home, in a calm spot.`,
          `Set a phone reminder for tomorrow to check in on how you feel.`,
          `Keep ${product} in a place that's safe from kids and pets.`,
        ],
      };
    case "watch_for":
      return {
        body:
          `Most people feel fine. But call us right away if you feel: ` +
          `racing heart, trouble breathing, very confused, very anxious, or you can't keep food down. ` +
          `For real emergencies (like chest pain) — call 911.`,
      };
    case "lifestyle":
      return {
        body:
          `A 10-minute walk + good sleep amplifies everything we're doing. ` +
          `Drink water, take rest seriously, and don't be afraid to message us with questions.`,
      };
    case "calm_tools":
      return {
        body:
          `Try the 4-7-8 breath: in for 4, hold for 7, out for 8. ` +
          `It sounds simple, but it works because your body trusts your breath.`,
      };
    case "grounding":
      return {
        body:
          `When things feel overwhelming, try the 5-4-3-2-1 trick: name 5 things you see, ` +
          `4 things you can touch, 3 things you hear, 2 things you smell, and 1 thing you taste.`,
      };
    case "questions":
      return {
        body:
          `Write down the questions that pop into your head — even if they feel small. ` +
          `Bring the list to your next visit.`,
      };
    case "plan":
      return {
        body: `Take ${dose} ${schedule}. ` + (topic.visitNotes ?? ""),
      };
    default:
      return { body: "" };
  }
}

function plainLanguageForDiagnosis(icd10: string): string {
  const code = icd10.toUpperCase();
  if (code.startsWith("G89")) return "you've been having pain that just won't quit";
  if (code === "G47.00") return "your brain isn't giving you the rest you need";
  if (code === "F41.1") return "your brain has been on a high-alert setting too often";
  if (code === "F43.10") return "your nervous system is still on guard from something hard";
  if (code === "F32.9" || code.startsWith("F33"))
    return "your mood has been low for a while and we're going to help lift it";
  if (code === "M79.7")
    return "your body sends pain signals more loudly than other folks";
  if (code === "G35") return "your nerves' insulation needs some help";
  if (code.startsWith("G40")) return "your brain has unexpected electrical bursts";
  return "the thing we talked about today";
}

// ---------------------------------------------------------------------------
// LLM-mode body
// ---------------------------------------------------------------------------

async function llmBody(
  blueprint: { sectionId: string; emoji: string; heading: string }[],
  topic: EducationSheetTopic,
  patient: PatientContextForEducation,
  model: ModelClient,
): Promise<{ source: "llm"; sections: EducationSheetSection[]; modelLabel: string }> {
  // Build a single prompt that returns a JSON array of sections so we
  // only spend one LLM call per sheet.
  const prompt = buildPrompt(blueprint, topic, patient);
  const raw = await model.complete(prompt, { temperature: 0.4, maxTokens: 900 });
  let parsed: Array<{ sectionId: string; body: string; actions?: string[] }> = [];
  try {
    const start = raw.indexOf("[");
    const end = raw.lastIndexOf("]");
    if (start >= 0 && end > start) {
      parsed = JSON.parse(raw.slice(start, end + 1));
    }
  } catch {
    parsed = [];
  }
  const byId = new Map(parsed.map((p) => [p.sectionId, p]));
  const sections: EducationSheetSection[] = blueprint.map((b) => {
    const llm = byId.get(b.sectionId);
    if (llm && typeof llm.body === "string" && llm.body.length > 0) {
      return {
        id: b.sectionId,
        emoji: b.emoji,
        heading: b.heading,
        body: llm.body,
        actions: llm.actions,
      };
    }
    const fallback = templateBody(b.sectionId, topic, patient);
    return {
      id: b.sectionId,
      emoji: b.emoji,
      heading: b.heading,
      body: fallback.body,
      actions: fallback.actions,
    };
  });
  return { source: "llm", sections, modelLabel: "configured-model" };
}

function buildPrompt(
  blueprint: { sectionId: string; emoji: string; heading: string }[],
  topic: EducationSheetTopic,
  patient: PatientContextForEducation,
): string {
  const product = topic.product
    ? `${topic.product.name}${topic.product.formulation ? ` (${topic.product.formulation})` : ""}` +
      `${topic.product.dose ? `, dose ${topic.product.dose}` : ""}` +
      `${topic.product.schedule ? `, schedule ${topic.product.schedule}` : ""}`
    : "no specific product";
  const guardianAddendum = patient.hasGuardian
    ? `Patient is a minor; guardian is ${patient.guardianName ?? "on file"}. Address sections to the guardian where appropriate.\n`
    : "";
  return [
    `You are writing a patient education sheet for ${patient.firstName}, age ${patient.age ?? "unknown"} (${patient.ageBand}).`,
    `Diagnosis: ${topic.diagnosisLabel} (${topic.icd10}).`,
    `Product/medicine: ${product}.`,
    `Visit notes from clinician: ${topic.visitNotes ?? "none"}.`,
    guardianAddendum,
    `Tone: warm, third-grade reading level, no medical jargon.`,
    `Language: ${patient.preferredLanguage === "es" ? "Spanish" : "English"}.`,
    `Output strictly a JSON array. Each item is { "sectionId": string, "body": string, "actions"?: string[] }.`,
    `Use these sectionIds in this order: ${blueprint.map((b) => b.sectionId).join(", ")}.`,
    `Do not include the headings or emojis — those are added by the renderer.`,
    `Each body should be 2–4 short sentences.`,
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Public entry
// ---------------------------------------------------------------------------

export interface GenerateEducationSheetOptions {
  topic: EducationSheetTopic;
  patient: PatientContextForEducation;
  /** Optional model client — when present, LLM mode is used. */
  model?: ModelClient;
}

export async function generateEducationSheet({
  topic,
  patient,
  model,
}: GenerateEducationSheetOptions): Promise<EducationSheet> {
  const language = patient.preferredLanguage ?? "en";
  const blueprint =
    SECTION_BLUEPRINT_BY_ICD[topic.icd10.toUpperCase()] ?? DEFAULT_BLUEPRINT;

  let sections: EducationSheetSection[];
  let source: "llm" | "template" = "template";
  let modelLabel: string | undefined;

  if (model) {
    try {
      const built = await llmBody(blueprint, topic, patient, model);
      sections = built.sections;
      source = built.source;
      modelLabel = built.modelLabel;
    } catch {
      sections = blueprint.map((b) => {
        const t = templateBody(b.sectionId, topic, patient);
        return {
          id: b.sectionId,
          emoji: b.emoji,
          heading: b.heading,
          body: t.body,
          actions: t.actions,
        };
      });
    }
  } else {
    sections = blueprint.map((b) => {
      const t = templateBody(b.sectionId, topic, patient);
      return {
        id: b.sectionId,
        emoji: b.emoji,
        heading: b.heading,
        body: t.body,
        actions: t.actions,
      };
    });
  }

  // Guardian addendum (minor)
  if (patient.hasGuardian) {
    sections.push({
      id: "guardian",
      emoji: "🪪",
      heading: "Note for guardian",
      body:
        `${patient.guardianName ?? "Guardian"}, please review this plan with ${patient.firstName} ` +
        `and call us if anything is unclear before the next dose.`,
    });
  }

  // Flag addendum (allergies, etc.)
  if (patient.flags && patient.flags.length > 0) {
    sections.push({
      id: "flags",
      emoji: "⚠️",
      heading: "Important reminders",
      body: patient.flags.map((f) => `• ${f}`).join("\n"),
    });
  }

  return {
    id: `edu-${topic.icd10}-${Date.now()}`,
    generatedAt: new Date().toISOString(),
    language,
    topic,
    sections,
    outcomeChecklist: outcomeChecklistForIcd(topic.icd10),
    references: referencesForIcd(topic.icd10),
    source,
    modelLabel,
  };
}

function referencesForIcd(icd: string): string[] {
  const code = icd.toUpperCase();
  if (code.startsWith("G89") || code === "M79.7") {
    return [
      "Whiting et al., 2015. JAMA. Cannabinoids for chronic pain.",
      "National Academies of Sciences, 2017. The health effects of cannabis.",
    ];
  }
  if (code === "G47.00") {
    return [
      "Babson et al., 2017. Cannabis, sleep, and dreaming.",
      "Suraev et al., 2020. Cannabinoid therapies for sleep — systematic review.",
    ];
  }
  if (code.startsWith("F41") || code.startsWith("F40")) {
    return [
      "Bergamaschi et al., 2011. CBD for social anxiety disorder.",
      "Skelley et al., 2020. CBD for anxiety — review.",
    ];
  }
  if (code === "F43.10") {
    return [
      "Bonn-Miller et al., 2021. Cannabis and PTSD — RCT.",
    ];
  }
  return ["See your clinician's notes for sources used in this sheet."];
}

// ---------------------------------------------------------------------------
// Helpers for the surrounding chart UI
// ---------------------------------------------------------------------------

export function plainTextSheet(sheet: EducationSheet): string {
  const lines: string[] = [];
  lines.push(`📄 ${sheet.topic.title}`);
  lines.push(`For: ${sheet.topic.diagnosisLabel}`);
  lines.push("");
  for (const s of sheet.sections) {
    lines.push(`${s.emoji} ${s.heading}`);
    lines.push(s.body);
    if (s.actions && s.actions.length > 0) {
      lines.push("");
      lines.push(s.actions.map((a) => `  • ${a}`).join("\n"));
    }
    lines.push("");
  }
  if (sheet.outcomeChecklist.length > 0) {
    lines.push("📊 How to track how you're doing");
    for (const p of sheet.outcomeChecklist) {
      lines.push(`  ${p.faces.join(" / ")}  ${p.question}`);
      lines.push(`     scale: ${p.scale.min}  →  ${p.scale.max}`);
    }
    lines.push("");
  }
  if (sheet.references.length > 0) {
    lines.push("📚 References");
    for (const r of sheet.references) lines.push(`  • ${r}`);
  }
  return lines.join("\n");
}
