"use client";
import React from "react";
import dynamic from "next/dynamic";

const PlatformDisclaimer = dynamic(() => import("@/components/layout/platform-disclaimer").then(mod => mod.PlatformDisclaimer), { ssr: false });
const StemIcon = dynamic(() => import("@/components/ui/cannabis-icons").then(mod => mod.StemIcon), { ssr: false });
const AmbientPlayer = dynamic(() => import("@/components/audio/ambient-player").then(mod => mod.AmbientPlayer), { ssr: false });
const VitalsCard = dynamic(() => import("@/components/patient/vitals-card").then(mod => mod.VitalsCard), { ssr: false });
const DocumentActions = dynamic(() => import("@/components/patient/document-actions").then(mod => mod.DocumentActions), { ssr: false });
const AffiliateProductCard = dynamic(() => import("@/components/store/affiliate-product-card").then(mod => mod.AffiliateProductCard), { ssr: false });
const KanderResources = dynamic(() => import("@/components/education/kander-resources").then(mod => mod.KanderResources), { ssr: false });
const HealthRoadmap = dynamic(() => import("@/components/patient/health-roadmap").then(mod => mod.HealthRoadmap), { ssr: false });
const LocatorMap = dynamic(() => import("@/components/dispensary/locator-map").then(mod => mod.LocatorMap), { ssr: false });
const DicomViewer = dynamic(() => import("@/components/dicom/dicom-viewer").then(mod => mod.DicomViewer), { ssr: false });
const PlantCompanion = dynamic(() => import("@/components/gamification/plant-companion").then(mod => mod.PlantCompanion), { ssr: false });
const HealthRings = dynamic(() => import("@/components/gamification/health-rings").then(mod => mod.HealthRings), { ssr: false });
const PositiveInputPrompt = dynamic(() => import("@/components/patient/positive-input-prompt").then(mod => mod.PositiveInputPrompt), { ssr: false });
const ComboWheelShell = dynamic(() => import("@/components/education/combo-wheel-shell").then(mod => mod.ComboWheelShell), { ssr: false });
const DosingDisplay = dynamic(() => import("@/components/prescription/dosing-display").then(mod => mod.DosingDisplay), { ssr: false });
const SleepHygieneCard = dynamic(() => import("@/components/lifestyle/sleep-hygiene-card").then(mod => mod.SleepHygieneCard), { ssr: false });
const MealPlanCard = dynamic(() => import("@/components/lifestyle/meal-plan-card").then(mod => mod.MealPlanCard), { ssr: false });
const ExerciseRegimenCard = dynamic(() => import("@/components/lifestyle/exercise-regimen-card").then(mod => mod.ExerciseRegimenCard), { ssr: false });
const StressReductionCard = dynamic(() => import("@/components/lifestyle/stress-reduction-card").then(mod => mod.StressReductionCard), { ssr: false });
const HabitFormationCard = dynamic(() => import("@/components/lifestyle/habit-formation-card").then(mod => mod.HabitFormationCard), { ssr: false });
const SocialConnectivityCard = dynamic(() => import("@/components/lifestyle/social-connectivity-card").then(mod => mod.SocialConnectivityCard), { ssr: false });


export default function ScaffoldGalleryPage() {
  return (
    <div className="min-h-screen bg-slate-50 py-12 px-6">
      <div className="max-w-7xl mx-auto">
        <h1 className="text-4xl font-bold text-slate-900 mb-4">Night Shift Swarm Components</h1>
        <p className="text-lg text-slate-600 mb-12">
          This gallery renders all 30 isolated components generated by the swarm, allowing you to preview and interact with them before wiring them into their final routes.
        </p>

        
        <div id="component-01" className="mb-12 border border-slate-200 rounded-xl overflow-hidden shadow-sm">
          <div className="bg-slate-100 px-4 py-2 border-b border-slate-200">
            <h2 className="font-mono text-sm font-semibold text-slate-700">Swarm ID: 01 - PlatformDisclaimer</h2>
            <p className="font-mono text-xs text-slate-500">src/components/layout/platform-disclaimer.tsx</p>
          </div>
          <div className="p-8 bg-white relative overflow-x-auto">
            <PlatformDisclaimer />
          </div>
        </div>

        <div id="component-02" className="mb-12 border border-slate-200 rounded-xl overflow-hidden shadow-sm">
          <div className="bg-slate-100 px-4 py-2 border-b border-slate-200">
            <h2 className="font-mono text-sm font-semibold text-slate-700">Swarm ID: 02 - StemIcon</h2>
            <p className="font-mono text-xs text-slate-500">src/components/ui/cannabis-icons.tsx</p>
          </div>
          <div className="p-8 bg-white relative overflow-x-auto">
            <StemIcon />
          </div>
        </div>

        <div id="component-03" className="mb-12 border border-slate-200 rounded-xl overflow-hidden shadow-sm">
          <div className="bg-slate-100 px-4 py-2 border-b border-slate-200">
            <h2 className="font-mono text-sm font-semibold text-slate-700">Swarm ID: 03 - AmbientPlayer</h2>
            <p className="font-mono text-xs text-slate-500">src/components/audio/ambient-player.tsx</p>
          </div>
          <div className="p-8 bg-white relative overflow-x-auto">
            <AmbientPlayer />
          </div>
        </div>

        <div id="component-04" className="mb-12 border border-slate-200 rounded-xl overflow-hidden shadow-sm">
          <div className="bg-slate-100 px-4 py-2 border-b border-slate-200">
            <h2 className="font-mono text-sm font-semibold text-slate-700">Swarm ID: 04 - VitalsCard</h2>
            <p className="font-mono text-xs text-slate-500">src/components/patient/vitals-card.tsx</p>
          </div>
          <div className="p-8 bg-white relative overflow-x-auto">
            <VitalsCard />
          </div>
        </div>

        <div id="component-05" className="mb-12 border border-slate-200 rounded-xl overflow-hidden shadow-sm">
          <div className="bg-slate-100 px-4 py-2 border-b border-slate-200">
            <h2 className="font-mono text-sm font-semibold text-slate-700">Swarm ID: 05 - DocumentActions</h2>
            <p className="font-mono text-xs text-slate-500">src/components/patient/document-actions.tsx</p>
          </div>
          <div className="p-8 bg-white relative overflow-x-auto">
            <DocumentActions documentId="demo-123" documentName="Clinical Summary.pdf" />
          </div>
        </div>

        <div id="component-06" className="mb-12 border border-slate-200 rounded-xl overflow-hidden shadow-sm">
          <div className="bg-slate-100 px-4 py-2 border-b border-slate-200">
            <h2 className="font-mono text-sm font-semibold text-slate-700">Swarm ID: 06 - AffiliateProductCard</h2>
            <p className="font-mono text-xs text-slate-500">src/components/store/affiliate-product-card.tsx</p>
          </div>
          <div className="p-8 bg-white relative overflow-x-auto">
            <AffiliateProductCard product={{ id: "1", name: "Volcano Medic 2", brand: "Storz & Bickel", category: "Vaporizer", price: 479.00, imageUrl: "", affiliateUrl: "#", rating: 4.9, discountBadge: "10% OFF" }} />
          </div>
        </div>

        <div id="component-07" className="mb-12 border border-slate-200 rounded-xl overflow-hidden shadow-sm">
          <div className="bg-slate-100 px-4 py-2 border-b border-slate-200">
            <h2 className="font-mono text-sm font-semibold text-slate-700">Swarm ID: 07 - KanderResources</h2>
            <p className="font-mono text-xs text-slate-500">src/components/education/kander-resources.tsx</p>
          </div>
          <div className="p-8 bg-white relative overflow-x-auto">
            <KanderResources />
          </div>
        </div>

        <div id="component-08" className="mb-12 border border-slate-200 rounded-xl overflow-hidden shadow-sm">
          <div className="bg-slate-100 px-4 py-2 border-b border-slate-200">
            <h2 className="font-mono text-sm font-semibold text-slate-700">Swarm ID: 08 - HealthRoadmap</h2>
            <p className="font-mono text-xs text-slate-500">src/components/patient/health-roadmap.tsx</p>
          </div>
          <div className="p-8 bg-white relative overflow-x-auto">
            <HealthRoadmap />
          </div>
        </div>

        <div id="component-09" className="mb-12 border border-slate-200 rounded-xl overflow-hidden shadow-sm">
          <div className="bg-slate-100 px-4 py-2 border-b border-slate-200">
            <h2 className="font-mono text-sm font-semibold text-slate-700">Swarm ID: 09 - LocatorMap</h2>
            <p className="font-mono text-xs text-slate-500">src/components/dispensary/locator-map.tsx</p>
          </div>
          <div className="p-8 bg-white relative overflow-x-auto">
            <LocatorMap />
          </div>
        </div>

        <div id="component-10" className="mb-12 border border-slate-200 rounded-xl overflow-hidden shadow-sm">
          <div className="bg-slate-100 px-4 py-2 border-b border-slate-200">
            <h2 className="font-mono text-sm font-semibold text-slate-700">Swarm ID: 10 - DicomViewer</h2>
            <p className="font-mono text-xs text-slate-500">src/components/dicom/dicom-viewer.tsx</p>
          </div>
          <div className="p-8 bg-white relative overflow-x-auto">
            <DicomViewer />
          </div>
        </div>

        <div id="component-11" className="mb-12 border border-slate-200 rounded-xl overflow-hidden shadow-sm">
          <div className="bg-slate-100 px-4 py-2 border-b border-slate-200">
            <h2 className="font-mono text-sm font-semibold text-slate-700">Swarm ID: 11 - PlantCompanion</h2>
            <p className="font-mono text-xs text-slate-500">src/components/gamification/plant-companion.tsx</p>
          </div>
          <div className="p-8 bg-white relative overflow-x-auto">
            <PlantCompanion />
          </div>
        </div>

        <div id="component-12" className="mb-12 border border-slate-200 rounded-xl overflow-hidden shadow-sm">
          <div className="bg-slate-100 px-4 py-2 border-b border-slate-200">
            <h2 className="font-mono text-sm font-semibold text-slate-700">Swarm ID: 12 - HealthRings</h2>
            <p className="font-mono text-xs text-slate-500">src/components/gamification/health-rings.tsx</p>
          </div>
          <div className="p-8 bg-white relative overflow-x-auto">
            <HealthRings />
          </div>
        </div>

        <div id="component-13" className="mb-12 border border-slate-200 rounded-xl overflow-hidden shadow-sm">
          <div className="bg-slate-100 px-4 py-2 border-b border-slate-200">
            <h2 className="font-mono text-sm font-semibold text-slate-700">Swarm ID: 13 - PositiveInputPrompt</h2>
            <p className="font-mono text-xs text-slate-500">src/components/patient/positive-input-prompt.tsx</p>
          </div>
          <div className="p-8 bg-white relative overflow-x-auto">
            <PositiveInputPrompt />
          </div>
        </div>

        <div id="component-14" className="mb-12 border border-slate-200 rounded-xl overflow-hidden shadow-sm">
          <div className="bg-slate-100 px-4 py-2 border-b border-slate-200">
            <h2 className="font-mono text-sm font-semibold text-slate-700">Swarm ID: 14 - ComboWheelShell</h2>
            <p className="font-mono text-xs text-slate-500">src/components/education/combo-wheel-shell.tsx</p>
          </div>
          <div className="p-8 bg-white relative overflow-x-auto">
            <ComboWheelShell />
          </div>
        </div>

        <div id="component-15" className="mb-12 border border-slate-200 rounded-xl overflow-hidden shadow-sm">
          <div className="bg-slate-100 px-4 py-2 border-b border-slate-200">
            <h2 className="font-mono text-sm font-semibold text-slate-700">Swarm ID: 15 - DosingDisplay</h2>
            <p className="font-mono text-xs text-slate-500">src/components/prescription/dosing-display.tsx</p>
          </div>
          <div className="p-8 bg-white relative overflow-x-auto">
            <DosingDisplay />
          </div>
        </div>

        <div id="component-16" className="mb-12 border border-slate-200 rounded-xl overflow-hidden shadow-sm">
          <div className="bg-slate-100 px-4 py-2 border-b border-slate-200">
            <h2 className="font-mono text-sm font-semibold text-slate-700">Swarm ID: 16 - SleepHygieneCard</h2>
            <p className="font-mono text-xs text-slate-500">src/components/lifestyle/sleep-hygiene-card.tsx</p>
          </div>
          <div className="p-8 bg-white relative overflow-x-auto">
            <SleepHygieneCard />
          </div>
        </div>

        <div id="component-17" className="mb-12 border border-slate-200 rounded-xl overflow-hidden shadow-sm">
          <div className="bg-slate-100 px-4 py-2 border-b border-slate-200">
            <h2 className="font-mono text-sm font-semibold text-slate-700">Swarm ID: 17 - MealPlanCard</h2>
            <p className="font-mono text-xs text-slate-500">src/components/lifestyle/meal-plan-card.tsx</p>
          </div>
          <div className="p-8 bg-white relative overflow-x-auto">
            <MealPlanCard />
          </div>
        </div>

        <div id="component-18" className="mb-12 border border-slate-200 rounded-xl overflow-hidden shadow-sm">
          <div className="bg-slate-100 px-4 py-2 border-b border-slate-200">
            <h2 className="font-mono text-sm font-semibold text-slate-700">Swarm ID: 18 - ExerciseRegimenCard</h2>
            <p className="font-mono text-xs text-slate-500">src/components/lifestyle/exercise-regimen-card.tsx</p>
          </div>
          <div className="p-8 bg-white relative overflow-x-auto">
            <ExerciseRegimenCard />
          </div>
        </div>

        <div id="component-19" className="mb-12 border border-slate-200 rounded-xl overflow-hidden shadow-sm">
          <div className="bg-slate-100 px-4 py-2 border-b border-slate-200">
            <h2 className="font-mono text-sm font-semibold text-slate-700">Swarm ID: 19 - StressReductionCard</h2>
            <p className="font-mono text-xs text-slate-500">src/components/lifestyle/stress-reduction-card.tsx</p>
          </div>
          <div className="p-8 bg-white relative overflow-x-auto">
            <StressReductionCard />
          </div>
        </div>

        <div id="component-20" className="mb-12 border border-slate-200 rounded-xl overflow-hidden shadow-sm">
          <div className="bg-slate-100 px-4 py-2 border-b border-slate-200">
            <h2 className="font-mono text-sm font-semibold text-slate-700">Swarm ID: 20 - HabitFormationCard</h2>
            <p className="font-mono text-xs text-slate-500">src/components/lifestyle/habit-formation-card.tsx</p>
          </div>
          <div className="p-8 bg-white relative overflow-x-auto">
            <HabitFormationCard />
          </div>
        </div>

        <div id="component-21" className="mb-12 border border-slate-200 rounded-xl overflow-hidden shadow-sm">
          <div className="bg-slate-100 px-4 py-2 border-b border-slate-200">
            <h2 className="font-mono text-sm font-semibold text-slate-700">Swarm ID: 21 - SocialConnectivityCard</h2>
            <p className="font-mono text-xs text-slate-500">src/components/lifestyle/social-connectivity-card.tsx</p>
          </div>
          <div className="p-8 bg-white relative overflow-x-auto">
            <SocialConnectivityCard />
          </div>
        </div>


      </div>
    </div>
  );
}
