import fs from "fs";
import path from "path";

function parseSwarmMatrix() {
  const content = fs.readFileSync(path.join(process.cwd(), "SWARM_MATRIX.md"), "utf8");
  const regex = /\| (\d+) \| [^|]+ \| [^|]+ \| `(src\/components\/[^`]+)` \|/g;
  let match;
  const components: { id: string; file: string; name: string }[] = [];

  while ((match = regex.exec(content)) !== null) {
    const id = match[1];
    const file = match[2];
    
    // Read the file to find the exported component name
    const filePath = path.join(process.cwd(), file);
    if (!fs.existsSync(filePath)) {
      console.warn(`File not found: ${file}`);
      continue;
    }

    const fileContent = fs.readFileSync(filePath, "utf8");
    const exportMatch = fileContent.match(/export (?:default )?(?:function|const) ([A-Za-z0-9_]+)/);
    if (exportMatch) {
      components.push({ id, file, name: exportMatch[1] });
    } else {
      console.warn(`Could not find export in: ${file}`);
    }
  }

  return components;
}

function generateGallery() {
  const components = parseSwarmMatrix();
  const imports = components.map((c) => {
    // Convert src/components/... to @/components/...
    const importPath = c.file.replace(/^src\//, "@/").replace(/\.tsx$/, "");
    return `const ${c.name} = dynamic(() => import("${importPath}").then(mod => mod.${c.name}), { ssr: false });`;
  }).join("\n");

  const renders = components.map((c) => {
    let props = "";
    if (c.name === "DocumentActions") {
      props = ` documentId="demo-123" documentName="Clinical Summary.pdf"`;
    } else if (c.name === "AffiliateProductCard") {
      props = ` product={{ id: "1", name: "Volcano Medic 2", brand: "Storz & Bickel", category: "Vaporizer", price: 479.00, imageUrl: "", affiliateUrl: "#", rating: 4.9, discountBadge: "10% OFF" }}`;
    }

    return `
        <div id="component-${c.id}" className="mb-12 border border-slate-200 rounded-xl overflow-hidden shadow-sm">
          <div className="bg-slate-100 px-4 py-2 border-b border-slate-200">
            <h2 className="font-mono text-sm font-semibold text-slate-700">Swarm ID: ${c.id} - ${c.name}</h2>
            <p className="font-mono text-xs text-slate-500">${c.file}</p>
          </div>
          <div className="p-8 bg-white relative overflow-x-auto">
            <${c.name}${props} />
          </div>
        </div>`;
  }).join("\n");

  const pageContent = `"use client";
import React from "react";
import dynamic from "next/dynamic";

${imports}

export default function ScaffoldGalleryPage() {
  return (
    <div className="min-h-screen bg-slate-50 py-12 px-6">
      <div className="max-w-7xl mx-auto">
        <h1 className="text-4xl font-bold text-slate-900 mb-4">Night Shift Swarm Components</h1>
        <p className="text-lg text-slate-600 mb-12">
          This gallery renders all 30 isolated components generated by the swarm, allowing you to preview and interact with them before wiring them into their final routes.
        </p>

        ${renders}
      </div>
    </div>
  );
}
`;

  const outDir = path.join(process.cwd(), "src/app/scaffold-gallery");
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  fs.writeFileSync(path.join(outDir, "page.tsx"), pageContent);
  console.log(`Successfully generated gallery with ${components.length} components at src/app/scaffold-gallery/page.tsx`);
}

generateGallery();
