// Run the auto-decomposer (Mallik's fallback automation) against a
// raw prompt file and emit a sibling `.auto.cards.md` with the
// rule-based output. Does NOT touch the database.
//
// This is NOT Mallik's real decomposition — Mallik's session pass
// lives at `<base>.cards.md` and is written by Claude-in-session.
//
// Usage:
//   npx tsx scripts/mallik-decompose.ts docs/product-prompts/patel-001-billing-insurance.md

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname, basename } from "node:path";
import {
  decomposePrompt,
  type LinearCard,
} from "../src/lib/agents/product-manager-agent";

function extractRawPrompt(md: string): string {
  // Pull the first fenced code block out of the markdown. That is the
  // canonical "raw prompt" section in our prompt files.
  const match = md.match(/```\s*\n([\s\S]*?)\n```/);
  if (!match) {
    throw new Error("No fenced code block (raw prompt) found in the prompt file.");
  }
  return match[1].trim();
}

function extractFrontMatter(md: string): Record<string, string> {
  const meta: Record<string, string> = {};
  const authorMatch = md.match(/\*\*Author:\*\*\s*([^\n]+)/);
  const sourceMatch = md.match(/\*\*Source:\*\*\s*([^\n]+)/);
  if (authorMatch) meta.author = authorMatch[1].trim();
  if (sourceMatch) meta.source = sourceMatch[1].trim();
  return meta;
}

function renderCard(card: LinearCard, idx: number): string {
  const lines: string[] = [];
  lines.push(`### ${idx + 1}. ${card.title}`);
  lines.push("");
  lines.push(`- **Priority:** ${card.priority}`);
  if (card.estimate) lines.push(`- **Estimate:** ${card.estimate}`);
  if (card.labels.length > 0) {
    lines.push(`- **Labels:** ${card.labels.map((l) => `\`${l}\``).join(", ")}`);
  }
  if (card.parentEpicSlug) lines.push(`- **Epic:** \`${card.parentEpicSlug}\``);
  if (card.dependsOn.length > 0) {
    lines.push(`- **Depends on:**`);
    for (const dep of card.dependsOn) lines.push(`  - ${dep}`);
  }
  lines.push("");
  lines.push(card.description);
  if (card.acceptanceCriteria.length > 0) {
    lines.push("");
    lines.push("**Acceptance criteria:**");
    for (const ac of card.acceptanceCriteria) lines.push(`- ${ac}`);
  }
  return lines.join("\n");
}

function main() {
  const [, , inputPath] = process.argv;
  if (!inputPath) {
    console.error("Usage: tsx scripts/mallik-decompose.ts <prompt-file.md>");
    process.exit(1);
  }

  const absInput = resolve(inputPath);
  const md = readFileSync(absInput, "utf8");
  const rawText = extractRawPrompt(md);
  const meta = extractFrontMatter(md);

  const source = meta.source?.toLowerCase().includes("imessage") ? "imessage" : meta.source ?? "manual";
  const author = meta.author?.toLowerCase().includes("patel") ? "dr_patel" : meta.author ?? "unknown";

  const result = decomposePrompt({ rawText, source, author });

  const base = basename(absInput, ".md");
  const outPath = resolve(dirname(absInput), `${base}.auto.cards.md`);

  const out: string[] = [];
  out.push(`# Auto pass — ${base}`);
  out.push("");
  out.push(
    `> **Not Mallik.** This is the rule-based auto-decomposer's output.\n` +
      `> Generated by \`agent:promptDecomposer@1.0.0\` from \`${base}.md\`.\n` +
      `> Mallik's session pass lives at \`${base}.cards.md\`.\n` +
      `> To regenerate: \`npx tsx scripts/mallik-decompose.ts docs/product-prompts/${base}.md\``,
  );
  out.push("");
  out.push(`## Epic`);
  out.push("");
  out.push(`**${result.epicTitle}** · \`${result.epicSlug}\``);
  out.push("");
  out.push(result.summary);
  out.push("");
  out.push(`## Cards (${result.cards.length})`);
  out.push("");
  for (const [idx, card] of result.cards.entries()) {
    out.push(renderCard(card, idx));
    out.push("");
  }
  out.push(`## Open questions (${result.openQuestions.length})`);
  out.push("");
  if (result.openQuestions.length === 0) {
    out.push("_None — Mallik understood everything._");
  } else {
    for (const q of result.openQuestions) out.push(`- ${q}`);
  }
  out.push("");

  writeFileSync(outPath, out.join("\n"), "utf8");
  console.log(`Wrote ${outPath}`);
  console.log(
    `  epic=${result.epicSlug} cards=${result.cards.length} openQuestions=${result.openQuestions.length}`,
  );
}

main();
