import type { MarketplaceProduct, MarketplaceCategory } from "./types";

// ---------------------------------------------------------------------------
// Categories
// ---------------------------------------------------------------------------

export const CATEGORIES: MarketplaceCategory[] = [
  { id: "cat-sleep", name: "Sleep", slug: "sleep", description: "Formulations designed to support restful, restorative sleep.", type: "symptom", icon: "\u263D", productCount: 3 },
  { id: "cat-pain", name: "Pain Support", slug: "pain-support", description: "Targeted relief for chronic and acute discomfort.", type: "symptom", icon: "\u2695", productCount: 3 },
  { id: "cat-anxiety", name: "Anxiety", slug: "anxiety", description: "Calming formulations for stress and anxious moments.", type: "symptom", icon: "\u2661", productCount: 3 },
  { id: "cat-nausea", name: "Nausea", slug: "nausea", description: "Fast-acting support for nausea and appetite.", type: "symptom", icon: "\u2606", productCount: 2 },
  { id: "cat-calm", name: "Calm", slug: "calm", description: "Gentle relaxation without heavy sedation.", type: "goal", icon: "\u2022", productCount: 4 },
  { id: "cat-focus", name: "Focus", slug: "focus", description: "Clarity and concentration support.", type: "goal", icon: "\u25C9", productCount: 2 },
  { id: "cat-recovery", name: "Recovery", slug: "recovery", description: "Post-activity and inflammation support.", type: "goal", icon: "\u21BB", productCount: 2 },
  { id: "cat-energy", name: "Energy", slug: "energy", description: "Uplifting formulations for daytime vitality.", type: "goal", icon: "\u2600", productCount: 2 },
  { id: "cat-tincture", name: "Tinctures", slug: "tinctures", description: "Precise sublingual dosing.", type: "format", icon: "\u2B22", productCount: 4 },
  { id: "cat-edible", name: "Edibles", slug: "edibles", description: "Measured-dose edible formulations.", type: "format", icon: "\u25CB", productCount: 2 },
  { id: "cat-topical", name: "Topicals", slug: "topicals", description: "Targeted external application.", type: "format", icon: "\u25A1", productCount: 2 },
  { id: "cat-capsule", name: "Capsules", slug: "capsules", description: "Consistent dosing in familiar form.", type: "format", icon: "\u2B24", productCount: 2 },
  { id: "cat-vape", name: "Vaporizers", slug: "vaporizers", description: "Fast-onset inhalation.", type: "format", icon: "\u2301", productCount: 2 },
  { id: "cat-clinician", name: "Clinician Picks", slug: "clinician-picks", description: "Selected by our care team for quality and efficacy.", type: "collection", icon: "\u2713", productCount: 5 },
  { id: "cat-best", name: "Best Sellers", slug: "best-sellers", description: "Our most trusted and reordered products.", type: "collection", icon: "\u2605", productCount: 4 },
  { id: "cat-beginner", name: "Beginner Friendly", slug: "beginner-friendly", description: "Low-dose, gentle formulations for new patients.", type: "collection", icon: "\u2192", productCount: 3 },
  { id: "cat-skin", name: "Skin", slug: "skin", description: "Plant-powered skin recovery and barrier support.", type: "goal", icon: "\u273f", productCount: 4 },
];

// ---------------------------------------------------------------------------
// Products
// ---------------------------------------------------------------------------

export const PRODUCTS: MarketplaceProduct[] = [
  {
    id: "prod-1",
    slug: "solace-nightfall-tincture",
    name: "Nightfall Sleep Tincture",
    brand: "Solace Botanicals",
    description: "A physician-formulated full-spectrum tincture combining CBN and CBD with calming terpenes for deep, restorative sleep. Designed for patients who need consistent nighttime support without next-morning grogginess. Third-party tested with a Certificate of Analysis available for every batch.",
    shortDescription: "CBN + CBD sleep tincture for deep, restorative rest.",
    price: 64,
    compareAtPrice: 78,
    status: "active",
    format: "tincture",
    imageUrl: undefined,
    images: [],
    thcContent: 2,
    cbdContent: 25,
    cbnContent: 10,
    terpeneProfile: { myrcene: 0.8, linalool: 0.6 },
    strainType: "indica",
    symptoms: ["Sleep", "Anxiety"],
    goals: ["Sleep", "Calm"],
    useCases: ["evening"],
    onsetTime: "20-40 minutes",
    duration: "6-8 hours",
    dosageGuidance: "Start with 0.5 mL under the tongue 30 minutes before bed. Increase to 1 mL after one week if needed.",
    beginnerFriendly: true,
    labVerified: true,
    clinicianPick: true,
    clinicianNote: "Our most recommended sleep formulation. The CBN-to-CBD ratio is well-suited for patients with racing thoughts at bedtime.",
    requires21Plus: true,
    inStock: true,
    averageRating: 4.8,
    reviewCount: 124,
    featured: true,
    categoryIds: ["cat-sleep", "cat-anxiety", "cat-calm", "cat-tincture", "cat-clinician", "cat-best", "cat-beginner"],
    variants: [
      { id: "v1a", name: "30 mL", upc: "850012345001", price: 64, compareAtPrice: 78, inStock: true },
      { id: "v1b", name: "60 mL", upc: "850012345002", price: 112, inStock: true },
    ],
    reviews: [
      { id: "r1a", authorName: "Sarah M.", rating: 5, title: "Finally sleeping through the night", body: "After years of poor sleep, this has been transformative. I fall asleep faster and stay asleep.", verified: true, createdAt: "2026-03-10" },
      { id: "r1b", authorName: "David R.", rating: 5, title: "Gentle and effective", body: "No grogginess in the morning. Exactly what I needed.", verified: true, createdAt: "2026-02-28" },
      { id: "r1c", authorName: "Priya K.", rating: 4, title: "Good results", body: "Took a few nights to find my dose but works well now.", verified: true, createdAt: "2026-02-15" },
    ],
  },
  {
    id: "prod-2",
    slug: "verdana-relief-balm",
    name: "Deep Relief Balm",
    brand: "Verdana Wellness",
    description: "A concentrated topical balm infused with full-spectrum cannabis extract, arnica, and menthol for targeted pain and inflammation relief. Apply directly to affected areas for localized support. Non-psychoactive and fast-absorbing.",
    shortDescription: "Full-spectrum topical for targeted pain and inflammation.",
    price: 48,
    status: "active",
    format: "topical",
    imageUrl: undefined,
    images: [],
    thcContent: 5,
    cbdContent: 30,
    terpeneProfile: { betaCaryophyllene: 1.2, limonene: 0.4 },
    strainType: "n/a",
    symptoms: ["Pain", "Inflammation", "Muscle tension"],
    goals: ["Recovery", "Pain support"],
    useCases: ["anytime"],
    onsetTime: "10-20 minutes",
    duration: "3-5 hours",
    dosageGuidance: "Apply a thin layer to the affected area and massage gently. Reapply every 4-6 hours as needed.",
    beginnerFriendly: true,
    labVerified: true,
    clinicianPick: true,
    clinicianNote: "Excellent for patients with localized joint or muscle discomfort who prefer non-systemic delivery.",
    inStock: true,
    averageRating: 4.7,
    reviewCount: 89,
    featured: true,
    categoryIds: ["cat-pain", "cat-recovery", "cat-topical", "cat-clinician", "cat-best", "cat-beginner"],
    variants: [
      { id: "v2a", name: "2 oz", upc: "850012345003", price: 48, inStock: true },
      { id: "v2b", name: "4 oz", upc: "850012345004", price: 82, inStock: true },
    ],
    reviews: [
      { id: "r2a", authorName: "Michael T.", rating: 5, title: "My knees thank me", body: "Applies smoothly and the relief kicks in fast. Using it daily now.", verified: true, createdAt: "2026-03-05" },
      { id: "r2b", authorName: "Linda W.", rating: 4, title: "Helpful for shoulder pain", body: "Noticeable improvement in about 15 minutes.", verified: true, createdAt: "2026-02-20" },
    ],
  },
  {
    id: "prod-3",
    slug: "canopy-clinical-balance-capsules",
    name: "Daily Balance Capsules",
    brand: "Canopy Clinical",
    description: "Precision-dosed CBD capsules designed for consistent daily wellness support. Each capsule delivers exactly 25 mg of broad-spectrum CBD in an easy-to-swallow softgel. Ideal for patients who value dosing consistency and convenience.",
    shortDescription: "25 mg CBD softgels for consistent daily wellness.",
    price: 54,
    status: "active",
    format: "capsule",
    imageUrl: undefined,
    images: [],
    thcContent: 0,
    cbdContent: 25,
    terpeneProfile: {},
    strainType: "n/a",
    symptoms: ["Anxiety", "Inflammation"],
    goals: ["Everyday wellness", "Calm"],
    useCases: ["morning", "anytime"],
    onsetTime: "45-90 minutes",
    duration: "6-8 hours",
    dosageGuidance: "Take one capsule daily with food. May increase to two capsules after 2 weeks under clinician guidance.",
    beginnerFriendly: true,
    labVerified: true,
    clinicianPick: true,
    clinicianNote: "The most approachable entry point for patients new to cannabinoid therapy. Zero THC, consistent dosing, familiar form factor.",
    requires21Plus: false,
    inStock: true,
    averageRating: 4.6,
    reviewCount: 67,
    featured: false,
    categoryIds: ["cat-anxiety", "cat-calm", "cat-capsule", "cat-clinician", "cat-beginner"],
    variants: [
      { id: "v3a", name: "30 count", upc: "850012345005", price: 54, inStock: true },
      { id: "v3b", name: "60 count", upc: "850012345006", price: 94, inStock: true },
    ],
    reviews: [
      { id: "r3a", authorName: "James L.", rating: 5, title: "Simple and effective", body: "Easy to take every morning. I feel more even throughout the day.", verified: true, createdAt: "2026-03-12" },
      { id: "r3b", authorName: "Karen S.", rating: 4, title: "Good daily supplement", body: "Took about a week to notice the difference but now I rely on it.", verified: true, createdAt: "2026-01-30" },
    ],
  },
  {
    id: "prod-4",
    slug: "solace-calm-drops",
    name: "Calm & Clarity Drops",
    brand: "Solace Botanicals",
    description: "A daytime-friendly tincture with a balanced THC:CBD ratio and uplifting terpenes. Designed for patients managing anxiety or stress during waking hours without sedation. Promotes calm focus and emotional equilibrium.",
    shortDescription: "Balanced THC:CBD drops for daytime calm without sedation.",
    price: 58,
    status: "active",
    format: "tincture",
    imageUrl: undefined,
    images: [],
    thcContent: 5,
    cbdContent: 20,
    terpeneProfile: { limonene: 0.7, pinene: 0.5 },
    strainType: "hybrid",
    symptoms: ["Anxiety"],
    goals: ["Calm", "Focus"],
    useCases: ["morning", "daytime"],
    onsetTime: "15-30 minutes",
    duration: "4-6 hours",
    dosageGuidance: "Start with 0.25 mL under the tongue. Hold for 60 seconds before swallowing. Adjust by 0.25 mL increments.",
    beginnerFriendly: false,
    labVerified: true,
    clinicianPick: false,
    clinicianNote: undefined,
    requires21Plus: true,
    inStock: true,
    averageRating: 4.5,
    reviewCount: 53,
    featured: true,
    categoryIds: ["cat-anxiety", "cat-calm", "cat-focus", "cat-tincture", "cat-best"],
    variants: [
      { id: "v4a", name: "30 mL", upc: "850012345007", price: 58, inStock: true },
    ],
    reviews: [
      { id: "r4a", authorName: "Anna C.", rating: 5, title: "Perfect for work days", body: "Keeps me relaxed without feeling foggy. Use it every morning.", verified: true, createdAt: "2026-03-01" },
    ],
  },
  {
    id: "prod-5",
    slug: "verdana-recovery-gel",
    name: "Recovery Cooling Gel",
    brand: "Verdana Wellness",
    description: "A fast-absorbing topical gel combining CBD with camphor and eucalyptus for post-exercise and chronic discomfort. The cooling sensation provides immediate comfort while cannabinoids work on deeper inflammation.",
    shortDescription: "CBD cooling gel for post-activity recovery.",
    price: 38,
    status: "active",
    format: "topical",
    imageUrl: undefined,
    images: [],
    thcContent: 0,
    cbdContent: 20,
    terpeneProfile: { eucalyptol: 0.5 },
    strainType: "n/a",
    symptoms: ["Pain", "Muscle tension", "Inflammation"],
    goals: ["Recovery"],
    useCases: ["anytime"],
    onsetTime: "5-15 minutes",
    duration: "2-4 hours",
    dosageGuidance: "Apply liberally to sore areas after activity. Reapply as needed.",
    beginnerFriendly: true,
    labVerified: true,
    clinicianPick: false,
    clinicianNote: undefined,
    inStock: true,
    averageRating: 4.4,
    reviewCount: 41,
    featured: false,
    categoryIds: ["cat-pain", "cat-recovery", "cat-topical"],
    variants: [
      { id: "v5a", name: "3 oz", upc: "850012345008", price: 38, inStock: true },
    ],
    reviews: [
      { id: "r5a", authorName: "Tom B.", rating: 4, title: "Great after the gym", body: "Cooling effect is immediate and the soreness fades within the hour.", verified: true, createdAt: "2026-02-18" },
    ],
  },
  {
    id: "prod-6",
    slug: "botanica-ease-gummies",
    name: "Ease Gummies",
    brand: "Botanica Therapeutics",
    description: "Precisely dosed THC:CBD gummies in a natural berry flavor. Each gummy delivers 5 mg THC and 10 mg CBD for gentle, approachable relief. Ideal for patients who prefer edible formats with predictable onset and duration.",
    shortDescription: "5 mg THC / 10 mg CBD gummies for gentle relief.",
    price: 36,
    status: "active",
    format: "edible",
    imageUrl: undefined,
    images: [],
    thcContent: 5,
    cbdContent: 10,
    terpeneProfile: {},
    strainType: "hybrid",
    symptoms: ["Pain", "Anxiety", "Nausea"],
    goals: ["Calm", "Pain support"],
    useCases: ["evening", "anytime"],
    onsetTime: "45-90 minutes",
    duration: "4-6 hours",
    dosageGuidance: "Start with one gummy. Wait at least 2 hours before considering a second. Do not exceed 4 gummies in 24 hours.",
    beginnerFriendly: false,
    labVerified: true,
    clinicianPick: true,
    clinicianNote: "A well-tolerated edible option for patients who dislike tinctures. The 2:1 CBD-to-THC ratio minimizes psychoactive intensity.",
    inStock: true,
    averageRating: 4.7,
    reviewCount: 98,
    featured: true,
    categoryIds: ["cat-pain", "cat-anxiety", "cat-nausea", "cat-calm", "cat-edible", "cat-clinician", "cat-best"],
    variants: [
      { id: "v6a", name: "20 count", upc: "850012345009", price: 36, inStock: true },
      { id: "v6b", name: "40 count", upc: "850012345010", price: 64, inStock: true },
    ],
    reviews: [
      { id: "r6a", authorName: "Rachel N.", rating: 5, title: "Taste great, work well", body: "These are my nightly go-to. Perfect dose for winding down.", verified: true, createdAt: "2026-03-08" },
      { id: "r6b", authorName: "Greg P.", rating: 5, title: "Exactly right", body: "Not too strong, not too weak. And they actually taste good.", verified: true, createdAt: "2026-02-25" },
    ],
  },
  {
    id: "prod-7",
    slug: "canopy-clinical-focus-capsules",
    name: "Focus Support Capsules",
    brand: "Canopy Clinical",
    description: "Microdose THC capsules with L-theanine and lion's mane extract for cognitive clarity and sustained attention. Designed for patients seeking gentle cannabinoid support during work or study without impairment.",
    shortDescription: "Microdose THC + nootropic capsules for focus.",
    price: 62,
    status: "active",
    format: "capsule",
    imageUrl: undefined,
    images: [],
    thcContent: 2.5,
    cbdContent: 5,
    terpeneProfile: { pinene: 0.6, terpinolene: 0.3 },
    strainType: "sativa",
    symptoms: [],
    goals: ["Focus", "Energy"],
    useCases: ["morning", "daytime"],
    onsetTime: "30-60 minutes",
    duration: "4-6 hours",
    dosageGuidance: "Take one capsule in the morning with food. Do not exceed two capsules daily.",
    beginnerFriendly: false,
    labVerified: true,
    clinicianPick: false,
    clinicianNote: undefined,
    inStock: true,
    averageRating: 4.3,
    reviewCount: 34,
    featured: false,
    categoryIds: ["cat-focus", "cat-energy", "cat-capsule"],
    variants: [
      { id: "v7a", name: "30 count", upc: "850012345011", price: 62, inStock: true },
    ],
    reviews: [
      { id: "r7a", authorName: "Mark J.", rating: 4, title: "Subtle but real", body: "Helps me stay on task without the jitters of coffee. Takes about a week to notice.", verified: true, createdAt: "2026-03-02" },
    ],
  },
  {
    id: "prod-8",
    slug: "solace-restore-vape",
    name: "Restore Vaporizer",
    brand: "Solace Botanicals",
    description: "A disposable all-in-one vaporizer with a strain-specific indica extract for fast-acting evening relief. Designed for patients who need rapid onset for acute symptoms like pain flares or insomnia episodes.",
    shortDescription: "Fast-acting indica vaporizer for evening relief.",
    price: 44,
    status: "active",
    format: "vape",
    imageUrl: undefined,
    images: [],
    thcContent: 75,
    cbdContent: 5,
    terpeneProfile: { myrcene: 1.2, linalool: 0.8 },
    strainType: "indica",
    symptoms: ["Pain", "Sleep"],
    goals: ["Sleep", "Calm"],
    useCases: ["evening"],
    onsetTime: "1-5 minutes",
    duration: "1-3 hours",
    dosageGuidance: "Start with one small inhalation. Wait 10 minutes before additional use. For experienced patients only.",
    beginnerFriendly: false,
    labVerified: true,
    clinicianPick: false,
    clinicianNote: undefined,
    inStock: true,
    averageRating: 4.5,
    reviewCount: 56,
    featured: false,
    categoryIds: ["cat-pain", "cat-sleep", "cat-calm", "cat-vape"],
    variants: [
      { id: "v8a", name: "0.5 g", upc: "850012345012", price: 44, inStock: true },
      { id: "v8b", name: "1 g", upc: "850012345013", price: 72, inStock: true },
    ],
    reviews: [
      { id: "r8a", authorName: "Chris D.", rating: 5, title: "Instant relief", body: "When my back flares up, this is the fastest thing that helps. Use sparingly.", verified: true, createdAt: "2026-02-14" },
    ],
  },
  {
    id: "prod-9",
    slug: "botanica-soothe-softgels",
    name: "Soothe Softgels",
    brand: "Botanica Therapeutics",
    description: "Anti-nausea softgels combining THC, CBD, and ginger extract. Formulated for patients experiencing treatment-related nausea, appetite loss, or digestive discomfort. Enteric-coated for gentle stomach absorption.",
    shortDescription: "THC + CBD + ginger softgels for nausea support.",
    price: 46,
    status: "active",
    format: "capsule",
    imageUrl: undefined,
    images: [],
    thcContent: 5,
    cbdContent: 10,
    terpeneProfile: { betaCaryophyllene: 0.4 },
    strainType: "hybrid",
    symptoms: ["Nausea", "Appetite"],
    goals: ["Everyday wellness"],
    useCases: ["morning", "anytime"],
    onsetTime: "30-60 minutes",
    duration: "4-6 hours",
    dosageGuidance: "Take one softgel 30 minutes before meals or as needed. Maximum three per day.",
    beginnerFriendly: false,
    labVerified: true,
    clinicianPick: true,
    clinicianNote: "Our preferred recommendation for chemotherapy-adjacent nausea support. The ginger extract adds complementary antiemetic benefit.",
    inStock: true,
    averageRating: 4.6,
    reviewCount: 45,
    featured: false,
    categoryIds: ["cat-nausea", "cat-capsule", "cat-clinician"],
    variants: [
      { id: "v9a", name: "30 count", upc: "850012345014", price: 46, inStock: true },
    ],
    reviews: [
      { id: "r9a", authorName: "Susan H.", rating: 5, title: "Game changer during treatment", body: "These made my chemo weeks so much more manageable. Grateful.", verified: true, createdAt: "2026-01-20" },
    ],
  },
  {
    id: "prod-10",
    slug: "verdana-uplift-tincture",
    name: "Uplift Daytime Tincture",
    brand: "Verdana Wellness",
    description: "A sativa-forward tincture with energizing terpenes for patients who need daytime vitality support. Low THC with moderate CBD for a clear-headed, uplifting experience without sedation or impairment.",
    shortDescription: "Sativa-forward tincture for daytime energy and mood.",
    price: 52,
    status: "active",
    format: "tincture",
    imageUrl: undefined,
    images: [],
    thcContent: 3,
    cbdContent: 15,
    terpeneProfile: { limonene: 0.9, pinene: 0.6 },
    strainType: "sativa",
    symptoms: [],
    goals: ["Energy", "Focus"],
    useCases: ["morning", "daytime"],
    onsetTime: "15-30 minutes",
    duration: "3-5 hours",
    dosageGuidance: "Start with 0.5 mL in the morning. May increase to 1 mL. Not recommended within 4 hours of bedtime.",
    beginnerFriendly: false,
    labVerified: true,
    clinicianPick: false,
    clinicianNote: undefined,
    inStock: true,
    averageRating: 4.4,
    reviewCount: 29,
    featured: false,
    categoryIds: ["cat-energy", "cat-focus", "cat-tincture"],
    variants: [
      { id: "v10a", name: "30 mL", upc: "850012345015", price: 52, inStock: true },
    ],
    reviews: [
      { id: "r10a", authorName: "Alicia F.", rating: 4, title: "Nice morning addition", body: "Gives me a gentle lift without any jitteriness.", verified: true, createdAt: "2026-03-15" },
    ],
  },
  {
    id: "prod-11",
    slug: "botanica-rest-gummies",
    name: "Rest & Restore Gummies",
    brand: "Botanica Therapeutics",
    description: "Nighttime gummies with CBN, CBD, and melatonin in a tart cherry flavor. Each gummy is formulated for sleep onset and maintenance. A gentler alternative to high-THC sleep products.",
    shortDescription: "CBN + melatonin gummies for natural sleep support.",
    price: 34,
    status: "active",
    format: "edible",
    imageUrl: undefined,
    images: [],
    thcContent: 0,
    cbdContent: 15,
    cbnContent: 5,
    terpeneProfile: { linalool: 0.4 },
    strainType: "n/a",
    symptoms: ["Sleep"],
    goals: ["Sleep"],
    useCases: ["evening"],
    onsetTime: "30-60 minutes",
    duration: "6-8 hours",
    dosageGuidance: "Take one gummy 45 minutes before bed. May take two if needed after the first week.",
    beginnerFriendly: true,
    labVerified: true,
    clinicianPick: false,
    clinicianNote: undefined,
    inStock: true,
    averageRating: 4.5,
    reviewCount: 72,
    featured: false,
    categoryIds: ["cat-sleep", "cat-edible", "cat-beginner"],
    variants: [
      { id: "v11a", name: "30 count", upc: "850012345016", price: 34, inStock: true },
      { id: "v11b", name: "60 count", upc: "850012345017", price: 58, inStock: true },
    ],
    reviews: [
      { id: "r11a", authorName: "Janet K.", rating: 5, title: "Better than melatonin alone", body: "The CBN makes a real difference. I fall asleep faster and stay asleep longer.", verified: true, createdAt: "2026-03-04" },
      { id: "r11b", authorName: "Robert M.", rating: 4, title: "Solid sleep aid", body: "Works well for me. Taste is good too.", verified: true, createdAt: "2026-02-10" },
    ],
  },
  {
    id: "prod-12",
    slug: "solace-tension-patch",
    name: "Tension Relief Patch",
    brand: "Solace Botanicals",
    description: "A transdermal patch delivering a steady 12-hour release of CBD and low-dose THC for sustained pain and tension management. Discreet, convenient, and ideal for patients who need all-day support without repeated dosing.",
    shortDescription: "12-hour transdermal patch for sustained pain relief.",
    price: 28,
    status: "active",
    format: "patch",
    imageUrl: undefined,
    images: [],
    thcContent: 5,
    cbdContent: 20,
    terpeneProfile: { betaCaryophyllene: 0.5 },
    strainType: "n/a",
    symptoms: ["Pain", "Muscle tension", "Inflammation"],
    goals: ["Pain support", "Recovery"],
    useCases: ["anytime"],
    onsetTime: "30-60 minutes",
    duration: "10-12 hours",
    dosageGuidance: "Apply one patch to a clean, dry area of skin. Remove after 12 hours. Rotate application sites.",
    beginnerFriendly: true,
    labVerified: true,
    clinicianPick: false,
    clinicianNote: undefined,
    inStock: true,
    averageRating: 4.3,
    reviewCount: 38,
    featured: false,
    categoryIds: ["cat-pain", "cat-recovery", "cat-beginner"],
    variants: [
      { id: "v12a", name: "4-pack", upc: "850012345018", price: 28, inStock: true },
      { id: "v12b", name: "8-pack", upc: "850012345019", price: 48, inStock: true },
    ],
    reviews: [
      { id: "r12a", authorName: "Paul V.", rating: 4, title: "Steady relief all day", body: "Put it on in the morning and forget about it. Very convenient.", verified: true, createdAt: "2026-02-22" },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // Leafmart storefront catalog — physician-curated cannabis wellness.
  // Branded by the four founding partners (PhytoRx, Flower Powered,
  // Greenleaf Co., Potency 710). Each row populates the new UI columns
  // (bgColor / deepColor / displayShape / doseLabel / outcomePct /
  // outcomeSampleSize) so the storefront mapper has authoritative data.
  // ─────────────────────────────────────────────────────────────────

  // ── Sleep shelf (6) ─────────────────────────────────────────────
  {
    id: "prod-13",
    slug: "stillwater-sleep-tonic",
    name: "Stillwater Sleep Tonic",
    brand: "PhytoRx",
    description: "A 25mg CBN tonic for the hour before bed. Made with magnesium glycinate, passionflower, and a quiet hint of lavender. Designed by our medical desk for patients with racing-thought insomnia.",
    shortDescription: "A 25mg CBN tonic for the hour before bed. Made with magnesium glycinate.",
    price: 32, status: "active", format: "beverage", images: [],
    thcContent: 0, cbdContent: 5, cbnContent: 25,
    terpeneProfile: { linalool: 0.6, myrcene: 0.4 },
    symptoms: ["Sleep", "Anxiety"], goals: ["Sleep", "Calm"], useCases: ["evening"],
    onsetTime: "30-45 minutes", duration: "5-7 hours",
    dosageGuidance: "Drink one bottle 45 minutes before bed.",
    beginnerFriendly: true, labVerified: true, clinicianPick: true,
    clinicianNote: "The CBN dosing is right where the literature suggests for sleep onset.",
    requires21Plus: false, inStock: true, averageRating: 4.55, reviewCount: 612, featured: true,
    bgColor: "var(--sage)", deepColor: "var(--leaf)", displayShape: "can",
    doseLabel: "12 fl oz · 25mg CBN", outcomePct: 81, outcomeSampleSize: 612,
    categoryIds: ["cat-sleep", "cat-clinician", "cat-best"],
    variants: [{ id: "v13a", name: "12 fl oz", upc: "850012345020", price: 32, inStock: true }],
    reviews: [
      { id: "r13a", authorName: "Maya R.", rating: 5, title: "Sleeps me through the night", body: "I'd been curious about CBN but didn't know where to start. This is now part of my evening.", verified: true, createdAt: "2026-03-22" },
    ],
  },
  {
    id: "prod-14",
    slug: "quiet-hours-tincture",
    name: "Quiet Hours Tincture",
    brand: "Greenleaf Co.",
    description: "Designed for evening wind-down routines. 1500mg CBD + 250mg CBN in MCT oil. Plant-powered, plainly labeled, with a Certificate of Analysis on every batch.",
    shortDescription: "Designed for evening wind-down routines. Plant-powered.",
    price: 64, status: "active", format: "tincture", images: [],
    thcContent: 0, cbdContent: 1500, cbnContent: 250,
    terpeneProfile: { linalool: 0.8, myrcene: 0.5 },
    symptoms: ["Sleep", "Anxiety"], goals: ["Sleep", "Calm"], useCases: ["evening"],
    onsetTime: "30-60 minutes", duration: "6-8 hours",
    dosageGuidance: "Start with 0.5 mL under the tongue, hold 60 seconds.",
    beginnerFriendly: true, labVerified: true, clinicianPick: false,
    requires21Plus: false, inStock: true, averageRating: 4.4, reviewCount: 502, featured: false,
    bgColor: "var(--butter)", deepColor: "#8A6A1F", displayShape: "bottle",
    doseLabel: "30ml · 1500mg", outcomePct: 79, outcomeSampleSize: 502,
    categoryIds: ["cat-sleep", "cat-tincture", "cat-best"],
    variants: [{ id: "v14a", name: "30 mL", upc: "850012345021", price: 64, inStock: true }],
    reviews: [{ id: "r14a", authorName: "Ben T.", rating: 4, title: "Reliable", body: "Steady, predictable.", verified: true, createdAt: "2026-03-12" }],
  },
  {
    id: "prod-15",
    slug: "twilight-capsules",
    name: "Twilight Capsules",
    brand: "PhytoRx",
    description: "Single-dose CBN capsules for the bedside drawer. 10mg CBN, 5mg CBD, 100mg L-theanine. Fast-melt vegan shell.",
    shortDescription: "Single-dose CBN capsules for the bedside drawer.",
    price: 42, status: "active", format: "capsule", images: [],
    thcContent: 0, cbdContent: 5, cbnContent: 10,
    symptoms: ["Sleep"], goals: ["Sleep"], useCases: ["evening"],
    onsetTime: "30-45 minutes", duration: "5-7 hours",
    dosageGuidance: "Take 1 capsule 45 minutes before bed.",
    beginnerFriendly: true, labVerified: true, clinicianPick: false,
    requires21Plus: false, inStock: true, averageRating: 4.3, reviewCount: 211, featured: false,
    bgColor: "var(--sage)", deepColor: "var(--leaf)", displayShape: "bottle",
    doseLabel: "30 ct · 10mg CBN", outcomePct: 76, outcomeSampleSize: 211,
    categoryIds: ["cat-sleep", "cat-capsule", "cat-beginner"],
    variants: [{ id: "v15a", name: "30 count", upc: "850012345022", price: 42, inStock: true }],
    reviews: [],
  },
  {
    id: "prod-16",
    slug: "lullaby-sleep-tea",
    name: "Lullaby Sleep Tea",
    brand: "Greenleaf Co.",
    description: "Caffeine-free chamomile and passionflower blend with 5mg CBN per sachet. Designed for the slow ritual of an evening cup.",
    shortDescription: "Chamomile + passionflower with 5mg CBN per sachet.",
    price: 28, status: "active", format: "edible", images: [],
    thcContent: 0, cbdContent: 0, cbnContent: 5,
    symptoms: ["Sleep"], goals: ["Sleep", "Calm"], useCases: ["evening"],
    onsetTime: "20-40 minutes", duration: "3-5 hours",
    dosageGuidance: "Steep one sachet 5 minutes in hot water.",
    beginnerFriendly: true, labVerified: true, clinicianPick: false,
    requires21Plus: false, inStock: true, averageRating: 4.2, reviewCount: 148, featured: false,
    bgColor: "var(--butter)", deepColor: "#8A6A1F", displayShape: "box",
    doseLabel: "20 sachets · 5mg CBN ea", outcomePct: 72, outcomeSampleSize: 148,
    categoryIds: ["cat-sleep", "cat-edible", "cat-beginner"],
    variants: [{ id: "v16a", name: "20 sachets", upc: "850012345023", price: 28, inStock: true }],
    reviews: [],
  },
  {
    id: "prod-17",
    slug: "drift-pillow-mist",
    name: "Drift Pillow Mist",
    brand: "Flower Powered",
    description: "A non-ingestible CBD-infused linen mist with lavender and chamomile hydrosols. Two sprays on the pillow before lights out.",
    shortDescription: "CBD pillow mist with lavender and chamomile hydrosols.",
    price: 26, status: "active", format: "topical", images: [],
    thcContent: 0, cbdContent: 50, cbnContent: 0,
    symptoms: ["Sleep"], goals: ["Sleep", "Calm"], useCases: ["evening"],
    beginnerFriendly: true, labVerified: true, clinicianPick: false,
    requires21Plus: false, inStock: true, averageRating: 4.1, reviewCount: 92, featured: false,
    bgColor: "var(--sage)", deepColor: "var(--leaf)", displayShape: "bottle",
    doseLabel: "120ml mist", outcomePct: 68, outcomeSampleSize: 92,
    categoryIds: ["cat-sleep", "cat-topical"],
    variants: [{ id: "v17a", name: "120 mL", upc: "850012345024", price: 26, inStock: true }],
    reviews: [],
  },
  {
    id: "prod-18",
    slug: "crescent-cbn-gummies",
    name: "Crescent CBN Gummies",
    brand: "Greenleaf Co.",
    description: "Soft pectin gummies, 10mg CBN with a touch of CBD. Discreet, predictable evening dosing.",
    shortDescription: "Soft pectin gummies, 10mg CBN with a touch of CBD.",
    price: 38, status: "active", format: "edible", images: [],
    thcContent: 0, cbdContent: 5, cbnContent: 10,
    symptoms: ["Sleep"], goals: ["Sleep"], useCases: ["evening"],
    onsetTime: "45-90 minutes", duration: "5-7 hours",
    beginnerFriendly: true, labVerified: true, clinicianPick: false,
    requires21Plus: false, inStock: true, averageRating: 4.35, reviewCount: 274, featured: false,
    bgColor: "var(--butter)", deepColor: "#8A6A1F", displayShape: "jar",
    doseLabel: "20 ct · 10mg CBN ea", outcomePct: 77, outcomeSampleSize: 274,
    categoryIds: ["cat-sleep", "cat-edible", "cat-beginner"],
    variants: [{ id: "v18a", name: "20 count", upc: "850012345025", price: 38, inStock: true }],
    reviews: [],
  },

  // ── Recovery shelf (5) ──────────────────────────────────────────
  {
    id: "prod-19",
    slug: "field-balm-no-4",
    name: "Field Balm № 4",
    brand: "Flower Powered",
    description: "A full-spectrum balm for everyday body tension after long days. 500mg CBD plus arnica, ginger, and a kiss of menthol.",
    shortDescription: "A full-spectrum balm for everyday body tension after long days.",
    price: 48, status: "active", format: "topical", images: [],
    thcContent: 2, cbdContent: 500, cbnContent: 0,
    terpeneProfile: { betaCaryophyllene: 1.0, limonene: 0.4 },
    symptoms: ["Pain", "Inflammation", "Muscle tension"], goals: ["Recovery", "Pain support"], useCases: ["after-activity"],
    beginnerFriendly: true, labVerified: true, clinicianPick: true,
    clinicianNote: "Our most-recommended topical for post-activity tension.",
    requires21Plus: false, inStock: true, averageRating: 4.45, reviewCount: 384, featured: true,
    bgColor: "var(--peach)", deepColor: "#9E5621", displayShape: "tin",
    doseLabel: "2oz · 500mg", outcomePct: 76, outcomeSampleSize: 384,
    categoryIds: ["cat-recovery", "cat-pain", "cat-topical", "cat-clinician", "cat-best"],
    variants: [
      { id: "v19a", name: "2 oz", upc: "850012345026", price: 48, inStock: true },
      { id: "v19b", name: "4 oz", upc: "850012345027", price: 84, inStock: true },
    ],
    reviews: [{ id: "r19a", authorName: "Daniel K.", rating: 5, title: "Now part of my recovery routine", body: "After a long ride this is the first thing I reach for.", verified: true, createdAt: "2026-03-08" }],
  },
  {
    id: "prod-20",
    slug: "trailhead-roll-on",
    name: "Trailhead Roll-on",
    brand: "Flower Powered",
    description: "A 750mg roll-on for targeted spots — knees, lower back, the side of the neck after a screen-heavy week.",
    shortDescription: "A 750mg roll-on for targeted spots.",
    price: 38, status: "active", format: "topical", images: [],
    thcContent: 0, cbdContent: 750, cbnContent: 0,
    symptoms: ["Pain", "Muscle tension"], goals: ["Recovery"], useCases: ["after-activity"],
    beginnerFriendly: true, labVerified: true, clinicianPick: false,
    requires21Plus: false, inStock: true, averageRating: 4.3, reviewCount: 196, featured: false,
    bgColor: "var(--peach)", deepColor: "#9E5621", displayShape: "bottle",
    doseLabel: "3oz · 750mg", outcomePct: 73, outcomeSampleSize: 196,
    categoryIds: ["cat-recovery", "cat-topical"],
    variants: [{ id: "v20a", name: "3 oz", upc: "850012345028", price: 38, inStock: true }],
    reviews: [],
  },
  {
    id: "prod-21",
    slug: "mineral-bath-soak",
    name: "Mineral Bath Soak",
    brand: "Flower Powered",
    description: "Magnesium chloride flakes infused with broad-spectrum CBD and eucalyptus. Two scoops in a hot bath after a long week.",
    shortDescription: "Magnesium + CBD bath soak for the full body unwind.",
    price: 34, status: "active", format: "topical", images: [],
    thcContent: 0, cbdContent: 200, cbnContent: 0,
    symptoms: ["Muscle tension", "Inflammation"], goals: ["Recovery", "Calm"], useCases: ["evening"],
    beginnerFriendly: true, labVerified: true, clinicianPick: false,
    requires21Plus: false, inStock: true, averageRating: 4.4, reviewCount: 142, featured: false,
    bgColor: "var(--peach)", deepColor: "#9E5621", displayShape: "jar",
    doseLabel: "16oz", outcomePct: 75, outcomeSampleSize: 142,
    categoryIds: ["cat-recovery", "cat-topical"],
    variants: [{ id: "v21a", name: "16 oz", upc: "850012345029", price: 34, inStock: true }],
    reviews: [],
  },
  {
    id: "prod-22",
    slug: "day-after-cream",
    name: "Day After Cream",
    brand: "Flower Powered",
    description: "A whipped 1000mg CBD cream for next-day soreness. Light, non-greasy, fast-absorbing.",
    shortDescription: "A whipped 1000mg CBD cream for next-day soreness.",
    price: 56, status: "active", format: "topical", images: [],
    thcContent: 0, cbdContent: 1000, cbnContent: 0,
    symptoms: ["Pain", "Inflammation"], goals: ["Recovery"], useCases: ["after-activity"],
    beginnerFriendly: true, labVerified: true, clinicianPick: false,
    requires21Plus: false, inStock: true, averageRating: 4.5, reviewCount: 168, featured: false,
    bgColor: "var(--peach)", deepColor: "#9E5621", displayShape: "tin",
    doseLabel: "4oz · 1000mg", outcomePct: 78, outcomeSampleSize: 168,
    categoryIds: ["cat-recovery", "cat-topical"],
    variants: [{ id: "v22a", name: "4 oz", upc: "850012345030", price: 56, inStock: true }],
    reviews: [],
  },
  {
    id: "prod-23",
    slug: "liniment-splash",
    name: "Liniment Splash",
    brand: "Flower Powered",
    description: "An old-school herbal liniment, modernized. Witch hazel, ginger, and 600mg full-spectrum CBD. Splash on after a bath.",
    shortDescription: "Modernized herbal liniment with 600mg CBD.",
    price: 32, status: "active", format: "topical", images: [],
    thcContent: 1, cbdContent: 600, cbnContent: 0,
    symptoms: ["Pain", "Muscle tension"], goals: ["Recovery"], useCases: ["after-activity"],
    beginnerFriendly: true, labVerified: true, clinicianPick: false,
    requires21Plus: false, inStock: true, averageRating: 4.25, reviewCount: 88, featured: false,
    bgColor: "var(--peach)", deepColor: "#9E5621", displayShape: "bottle",
    doseLabel: "8oz · 600mg", outcomePct: 71, outcomeSampleSize: 88,
    categoryIds: ["cat-recovery", "cat-topical"],
    variants: [{ id: "v23a", name: "8 oz", upc: "850012345031", price: 32, inStock: true }],
    reviews: [],
  },

  // ── Calm shelf (5) ──────────────────────────────────────────────
  {
    id: "prod-24",
    slug: "easy-hours-tincture",
    name: "Easy Hours Tincture",
    brand: "Greenleaf Co.",
    description: "A daytime CBD tincture with 750mg per bottle. Take 0.5mL when the day is louder than the head.",
    shortDescription: "A daytime CBD tincture for when the day is louder than the head.",
    price: 48, status: "active", format: "tincture", images: [],
    thcContent: 0, cbdContent: 750, cbnContent: 0,
    symptoms: ["Anxiety"], goals: ["Calm"], useCases: ["daytime"],
    onsetTime: "30-45 minutes", duration: "4-6 hours",
    beginnerFriendly: true, labVerified: true, clinicianPick: false,
    requires21Plus: false, inStock: true, averageRating: 4.3, reviewCount: 219, featured: false,
    bgColor: "var(--butter)", deepColor: "#8A6A1F", displayShape: "bottle",
    doseLabel: "30ml · 750mg", outcomePct: 74, outcomeSampleSize: 219,
    categoryIds: ["cat-calm", "cat-anxiety", "cat-tincture"],
    variants: [{ id: "v24a", name: "30 mL", upc: "850012345032", price: 48, inStock: true }],
    reviews: [],
  },
  {
    id: "prod-25",
    slug: "hum-beverage",
    name: "Hum",
    brand: "PhytoRx",
    description: "A quiet beverage for the late-afternoon. 15mg CBD + L-theanine + lemon balm.",
    shortDescription: "A quiet beverage for the late-afternoon. CBD + L-theanine.",
    price: 28, status: "active", format: "beverage", images: [],
    thcContent: 0, cbdContent: 15, cbnContent: 0,
    symptoms: ["Anxiety"], goals: ["Calm", "Focus"], useCases: ["daytime"],
    onsetTime: "20-30 minutes", duration: "2-3 hours",
    beginnerFriendly: true, labVerified: true, clinicianPick: false,
    requires21Plus: false, inStock: true, averageRating: 4.2, reviewCount: 161, featured: false,
    bgColor: "var(--butter)", deepColor: "#8A6A1F", displayShape: "can",
    doseLabel: "12 fl oz · CBD + L-theanine", outcomePct: 70, outcomeSampleSize: 161,
    categoryIds: ["cat-calm", "cat-anxiety"],
    variants: [{ id: "v25a", name: "12 fl oz", upc: "850012345033", price: 28, inStock: true }],
    reviews: [],
  },
  {
    id: "prod-26",
    slug: "settle-gummies",
    name: "Settle Gummies",
    brand: "Potency 710",
    description: "Low-dose 5mg CBD gummies for the kind of day where you take the edge off, gently.",
    shortDescription: "Low-dose 5mg CBD gummies. Take the edge off, gently.",
    price: 32, status: "active", format: "edible", images: [],
    thcContent: 0, cbdContent: 5, cbnContent: 0,
    symptoms: ["Anxiety"], goals: ["Calm"], useCases: ["daytime"],
    beginnerFriendly: true, labVerified: true, clinicianPick: false,
    requires21Plus: false, inStock: true, averageRating: 4.25, reviewCount: 184, featured: false,
    bgColor: "var(--butter)", deepColor: "#8A6A1F", displayShape: "jar",
    doseLabel: "30 ct · 5mg ea", outcomePct: 72, outcomeSampleSize: 184,
    categoryIds: ["cat-calm", "cat-edible", "cat-beginner"],
    variants: [{ id: "v26a", name: "30 count", upc: "850012345034", price: 32, inStock: true }],
    reviews: [],
  },
  {
    id: "prod-27",
    slug: "steady-drops",
    name: "Steady Drops",
    brand: "Greenleaf Co.",
    description: "1000mg of broad-spectrum CBD in MCT. The everyday tincture for people who want consistency, not surprises.",
    shortDescription: "1000mg broad-spectrum CBD. Everyday consistency.",
    price: 56, status: "active", format: "tincture", images: [],
    thcContent: 0, cbdContent: 1000, cbnContent: 0,
    symptoms: ["Anxiety"], goals: ["Calm", "Everyday wellness"], useCases: ["daytime"],
    onsetTime: "30-45 minutes", duration: "5-7 hours",
    beginnerFriendly: true, labVerified: true, clinicianPick: false,
    requires21Plus: false, inStock: true, averageRating: 4.35, reviewCount: 248, featured: false,
    bgColor: "var(--butter)", deepColor: "#8A6A1F", displayShape: "bottle",
    doseLabel: "30ml · 1000mg CBD", outcomePct: 75, outcomeSampleSize: 248,
    categoryIds: ["cat-calm", "cat-tincture"],
    variants: [{ id: "v27a", name: "30 mL", upc: "850012345035", price: 56, inStock: true }],
    reviews: [],
  },
  {
    id: "prod-28",
    slug: "pause-pen",
    name: "Pause Pen",
    brand: "Potency 710",
    description: "A 0.5g vape with a 1:1 CBD:CBG profile and a soft citrus terpene. A small dose, a small moment.",
    shortDescription: "0.5g 1:1 CBD:CBG vape with a soft citrus terpene.",
    price: 42, status: "active", format: "vape", images: [],
    thcContent: 0, cbdContent: 250, cbnContent: 0,
    terpeneProfile: { limonene: 0.9 },
    symptoms: ["Anxiety"], goals: ["Calm"], useCases: ["daytime"],
    beginnerFriendly: false, labVerified: true, clinicianPick: false,
    requires21Plus: true, inStock: true, averageRating: 4.1, reviewCount: 96, featured: false,
    bgColor: "var(--butter)", deepColor: "#8A6A1F", displayShape: "bottle",
    doseLabel: "0.5g · 1:1 CBD:CBG", outcomePct: 69, outcomeSampleSize: 96,
    categoryIds: ["cat-calm", "cat-vape"],
    variants: [{ id: "v28a", name: "0.5 g", upc: "850012345036", price: 42, inStock: true }],
    reviews: [],
  },

  // ── Skin shelf (4) ──────────────────────────────────────────────
  {
    id: "prod-29",
    slug: "gold-skin-serum",
    name: "Gold Skin Serum",
    brand: "Potency 710",
    description: "A clinician-reviewed serum for skin recovery and barrier support. 250mg of CBD, squalane, and a measured pinch of niacinamide.",
    shortDescription: "A clinician-reviewed serum for skin recovery and barrier support.",
    price: 84, status: "active", format: "serum", images: [],
    thcContent: 0, cbdContent: 250, cbnContent: 0,
    symptoms: ["Inflammation"], goals: ["Recovery"], useCases: ["skincare"],
    beginnerFriendly: true, labVerified: true, clinicianPick: true,
    clinicianNote: "Our dermatology consultant signed off on this one.",
    requires21Plus: false, inStock: true, averageRating: 4.6, reviewCount: 218, featured: true,
    bgColor: "var(--rose)", deepColor: "#9E4D45", displayShape: "serum",
    doseLabel: "30ml · 250mg", outcomePct: 73, outcomeSampleSize: 218,
    categoryIds: ["cat-skin", "cat-clinician"],
    variants: [{ id: "v29a", name: "30 mL", upc: "850012345037", price: 84, inStock: true }],
    reviews: [{ id: "r29a", authorName: "Priya S.", rating: 5, title: "Soothing", body: "It calmed my reactive skin within a week.", verified: true, createdAt: "2026-03-15" }],
  },
  {
    id: "prod-30",
    slug: "renewal-face-oil",
    name: "Renewal Face Oil",
    brand: "Potency 710",
    description: "Cold-pressed rosehip and jojoba blended with 100mg full-spectrum CBD. Three drops for the evening ritual.",
    shortDescription: "Cold-pressed rosehip + jojoba with 100mg full-spectrum CBD.",
    price: 68, status: "active", format: "serum", images: [],
    thcContent: 0, cbdContent: 100, cbnContent: 0,
    symptoms: ["Inflammation"], goals: ["Recovery"], useCases: ["skincare"],
    beginnerFriendly: true, labVerified: true, clinicianPick: false,
    requires21Plus: false, inStock: true, averageRating: 4.4, reviewCount: 134, featured: false,
    bgColor: "var(--rose)", deepColor: "#9E4D45", displayShape: "serum",
    doseLabel: "30ml · 100mg", outcomePct: 71, outcomeSampleSize: 134,
    categoryIds: ["cat-skin"],
    variants: [{ id: "v30a", name: "30 mL", upc: "850012345038", price: 68, inStock: true }],
    reviews: [],
  },
  {
    id: "prod-31",
    slug: "bloom-body-lotion",
    name: "Bloom Body Lotion",
    brand: "Potency 710",
    description: "A lightweight everyday lotion with 500mg CBD, shea, and a clean linen scent. For arms, shoulders, the back of the neck.",
    shortDescription: "A lightweight everyday lotion with 500mg CBD and shea.",
    price: 38, status: "active", format: "topical", images: [],
    thcContent: 0, cbdContent: 500, cbnContent: 0,
    symptoms: ["Inflammation"], goals: ["Everyday wellness"], useCases: ["skincare"],
    beginnerFriendly: true, labVerified: true, clinicianPick: false,
    requires21Plus: false, inStock: true, averageRating: 4.3, reviewCount: 102, featured: false,
    bgColor: "var(--rose)", deepColor: "#9E4D45", displayShape: "bottle",
    doseLabel: "8oz · 500mg", outcomePct: 70, outcomeSampleSize: 102,
    categoryIds: ["cat-skin", "cat-topical"],
    variants: [{ id: "v31a", name: "8 oz", upc: "850012345039", price: 38, inStock: true }],
    reviews: [],
  },
  {
    id: "prod-32",
    slug: "petal-cleanser",
    name: "Petal Cleanser",
    brand: "Potency 710",
    description: "A pH-balanced gel cleanser with 50mg full-spectrum CBD and rose water. Calms reactive skin without stripping it.",
    shortDescription: "Gel cleanser with 50mg CBD and rose water.",
    price: 32, status: "active", format: "topical", images: [],
    thcContent: 0, cbdContent: 50, cbnContent: 0,
    symptoms: ["Inflammation"], goals: ["Everyday wellness"], useCases: ["skincare"],
    beginnerFriendly: true, labVerified: true, clinicianPick: false,
    requires21Plus: false, inStock: true, averageRating: 4.1, reviewCount: 78, featured: false,
    bgColor: "var(--rose)", deepColor: "#9E4D45", displayShape: "bottle",
    doseLabel: "6oz · 50mg", outcomePct: 67, outcomeSampleSize: 78,
    categoryIds: ["cat-skin", "cat-topical"],
    variants: [{ id: "v32a", name: "6 oz", upc: "850012345040", price: 32, inStock: true }],
    reviews: [],
  },

  // ── Focus shelf (1) — rounds out the homepage's five shelves ───
  {
    id: "prod-33",
    slug: "clear-mornings-tincture",
    name: "Clear Mornings Tincture",
    brand: "PhytoRx",
    description: "A daytime CBG-forward tincture for the pre-coffee window. 500mg CBG + 250mg CBD with a citrus-pinene profile.",
    shortDescription: "A daytime CBG-forward tincture for the pre-coffee window.",
    price: 58, status: "active", format: "tincture", images: [],
    thcContent: 0, cbdContent: 250, cbnContent: 0,
    terpeneProfile: { limonene: 0.7, pinene: 0.5 },
    symptoms: [], goals: ["Focus", "Energy"], useCases: ["morning"],
    onsetTime: "30 minutes", duration: "3-5 hours",
    beginnerFriendly: true, labVerified: true, clinicianPick: false,
    requires21Plus: false, inStock: true, averageRating: 4.2, reviewCount: 112, featured: false,
    bgColor: "var(--lilac)", deepColor: "#5C4972", displayShape: "bottle",
    doseLabel: "30ml · 500mg CBG", outcomePct: 70, outcomeSampleSize: 112,
    categoryIds: ["cat-focus", "cat-tincture", "cat-energy"],
    variants: [{ id: "v33a", name: "30 mL", upc: "850012345041", price: 58, inStock: true }],
    reviews: [],
  },
];

// ---------------------------------------------------------------------------
// Query helpers
// ---------------------------------------------------------------------------

export function getProductBySlug(slug: string): MarketplaceProduct | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByCategory(categorySlug: string): MarketplaceProduct[] {
  const cat = CATEGORIES.find((c) => c.slug === categorySlug);
  if (!cat) return [];
  return PRODUCTS.filter((p) => p.categoryIds.includes(cat.id));
}

export function getFeaturedProducts(): MarketplaceProduct[] {
  return PRODUCTS.filter((p) => p.featured);
}

export function getClinicianPicks(): MarketplaceProduct[] {
  return PRODUCTS.filter((p) => p.clinicianPick);
}

export function searchProducts(query: string): MarketplaceProduct[] {
  const q = query.toLowerCase().trim();
  if (!q) return PRODUCTS;
  return PRODUCTS.filter((p) => {
    const haystack = [
      p.name, p.brand, p.description, p.shortDescription,
      ...p.symptoms, ...p.goals, ...p.useCases, p.format,
    ].join(" ").toLowerCase();
    return haystack.includes(q);
  });
}

export function getRelatedProducts(productId: string, limit = 4): MarketplaceProduct[] {
  const product = PRODUCTS.find((p) => p.id === productId);
  if (!product) return [];
  return PRODUCTS
    .filter((p) => p.id !== productId)
    .map((p) => {
      const shared = [...p.symptoms, ...p.goals].filter(
        (t) => [...product.symptoms, ...product.goals].includes(t)
      ).length;
      return { product: p, score: shared };
    })
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map((r) => r.product);
}

export function getCategoryBySlug(slug: string): MarketplaceCategory | undefined {
  return CATEGORIES.find((c) => c.slug === slug);
}

export function getCategories(type?: string): MarketplaceCategory[] {
  if (!type) return CATEGORIES;
  return CATEGORIES.filter((c) => c.type === type);
}
